import random
import string
import psycopg
import pytest


DJANGO_DB_CONN_STR = "postgresql://mathesar:mathesar@mathesar_dev_db:5432/mathesar_django"

@pytest.fixture(scope="session")
def db_init():
    with psycopg.connect(DJANGO_DB_CONN_STR, autocommit=True) as init_conn:
        db_name = f"mathesar_tests_{''.join(random.choices(string.ascii_lowercase, k=10))}" 
        init_conn.execute(f"CREATE DATABASE {db_name}")
    yield db_name
    with psycopg.connect(DJANGO_DB_CONN_STR, autocommit=True) as teardown_conn:
        teardown_conn.execute(f"DROP DATABASE {db_name} WITH (FORCE)")


@pytest.fixture
def db_conn(db_init):
    conn = psycopg.connect(f"postgresql://mathesar:mathesar@mathesar_dev_db:5432/{db_init}")
    with conn.transaction(force_rollback=True):
        yield conn
    conn.close()


@pytest.fixture
def manytypes(db_conn):
    db_conn.execute(
        """
        CREATE TABLE manytypes (
            id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            -- To fend off likely typos, we check many combinations of field and precision settings.
            ivl_plain interval,
            ivl_yr interval year,
            ivl_mo interval month,
            ivl_dy interval day,
            ivl_hr interval hour,
            ivl_mi interval minute,
            ivl_se interval second,
            ivl_ye_mo interval year to month,
            ivl_dy_hr interval day to hour,
            ivl_dy_mi interval day to minute,
            ivl_dy_se interval day to second,
            ivl_hr_mi interval hour to minute,
            ivl_hr_se interval hour to second,
            ivl_mi_se interval minute to second,
            ivl_se_0 interval second(0),
            ivl_se_3 interval second(3),
            ivl_se_6 interval second(6),
            ivl_dy_se0 interval day to second(0),
            ivl_dy_se3 interval day to second(3),
            ivl_dy_se6 interval day to second(6),
            ivl_hr_se0 interval hour to second(0),
            ivl_hr_se3 interval hour to second(3),
            ivl_hr_se6 interval hour to second(6),
            ivl_mi_se0 interval minute to second(0),
            ivl_mi_se3 interval minute to second(3),
            ivl_mi_se6 interval minute to second(6),
            -- Below here is less throrough, more ad-hoc
            ivl_plain_arr interval[],
            ivl_mi_se6_arr interval minute to second(6)[2][2],
            num_plain numeric,
            num_8 numeric(8),
            num_17_2 numeric(17, 2),
            num_plain_arr numeric[],
            num_17_2_arr numeric(17, 2)[],
            var_plain varchar,
            var_16 varchar(16),
            var_255 varchar(255),
            cha_1 character,
            cha_20 character(20),
            var_16_arr varchar(16)[],
            cha_20_arr character(20)[][],
            bit_8 bit(8),
            vbt_8 varbit(8),
            tim_2 time(2),
            ttz_3 timetz(3),
            tsp_4 timestamp(4),
            tsz_5 timestamptz(5)
        );
        """
    )
    return db_conn
