CREATE TABLE "Customers" (
    id integer NOT NULL,
    first_name text NOT NULL,
    last_name text NOT NULL,
    email mathesar_types.email,
    phone text
);

ALTER TABLE "Customers" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Customers_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE "Equipment" (
    id integer NOT NULL,
    type_id integer,
    serial_number text NOT NULL,
    notes text
);

CREATE TABLE "Equipment Types" (
    id integer NOT NULL,
    name text NOT NULL
);

ALTER TABLE "Equipment Types" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Equipment Types_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE "Equipment" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Equipment_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE "Mechanics" (
    id integer NOT NULL,
    first_name text NOT NULL,
    last_name text NOT NULL
);

ALTER TABLE "Mechanics" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Mechanics_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE "Service Milestones" (
    id integer NOT NULL,
    service_request_id integer,
    status_id integer,
    update_time timestamp without time zone DEFAULT now(),
    notes text
);

ALTER TABLE "Service Milestones" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Service Milestones_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE "Service Requests" (
    id integer NOT NULL,
    customer_id integer,
    equipment_id integer,
    mechanic_id integer,
    request_description text NOT NULL,
    cost mathesar_types.mathesar_money,
    time_in timestamp without time zone,
    time_out timestamp without time zone
);

ALTER TABLE "Service Requests" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Service Requests_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE "Service Statuses" (
    id integer NOT NULL,
    name text NOT NULL
);

ALTER TABLE "Service Statuses" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Service Statuses_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

INSERT INTO "Customers" VALUES (1, 'Dana', 'Hammond', 'brianlucero@example.net', '500.434.0936x02343');
INSERT INTO "Customers" VALUES (2, 'Andrew', 'Haley', 'qjackson@example.com', '402-383-1537');
INSERT INTO "Customers" VALUES (3, 'Latoya', 'Ryan', 'amystanton@example.org', '5734421348');
INSERT INTO "Customers" VALUES (4, 'Luis', 'Craig', 'garyowens@example.org', '764-473-7881');
INSERT INTO "Customers" VALUES (5, 'Anna', 'Wilson', 'patricialogan@example.org', '+1-596-698-4888');
INSERT INTO "Customers" VALUES (6, 'Jennifer', 'Jones', 'andrew77@example.net', '287-769-1758x09930');
INSERT INTO "Customers" VALUES (7, 'John', 'Dickson', 'ericgilbert@example.com', '4703913317');
INSERT INTO "Customers" VALUES (8, 'Joshua', 'Morrow', 'ydorsey@example.net', '2309613577');
INSERT INTO "Customers" VALUES (9, 'Tracy', 'Knapp', 'jonesmichael@example.com', '+1-507-277-0079x0202');
INSERT INTO "Customers" VALUES (10, 'Matthew', 'Castro', 'patrickhughes@example.net', '001-608-917-0321x7060');
INSERT INTO "Customers" VALUES (11, 'Alexis', 'Matthews', 'hermanpaul@example.org', '849-702-8934x365');
INSERT INTO "Customers" VALUES (12, 'Tracey', 'Arnold', 'suzanne42@example.com', '975.894.8159x7223');
INSERT INTO "Customers" VALUES (13, 'Jonathan', 'Kennedy', 'rogerschristopher@example.net', '(325)363-2885');
INSERT INTO "Customers" VALUES (14, 'Dawn', 'Martinez', 'vsmith@example.net', '001-881-825-7502');
INSERT INTO "Customers" VALUES (15, 'Elizabeth', 'Abbott', 'mccoykelly@example.com', '001-367-630-4020x2308');
INSERT INTO "Customers" VALUES (16, 'Lucas', 'Jones', 'taylorheather@example.net', '618.618.6664');
INSERT INTO "Customers" VALUES (17, 'Caitlin', 'Cohen', 'brittanymiller@example.net', '632.511.4592');
INSERT INTO "Customers" VALUES (18, 'Tamara', 'Williams', 'mary88@example.org', '240-204-5496');
INSERT INTO "Customers" VALUES (19, 'James', 'Smith', 'walkerkatherine@example.org', '6562600692');
INSERT INTO "Customers" VALUES (20, 'Mark', 'Ramos', 'javier21@example.net', '969.592.1524x3010');

INSERT INTO "Equipment" VALUES (1, 6, '6458772687570', '');
INSERT INTO "Equipment" VALUES (2, 4, '6594089210329', '');
INSERT INTO "Equipment" VALUES (3, 6, '5190009593483', '');
INSERT INTO "Equipment" VALUES (4, 4, '6718554847050', '');
INSERT INTO "Equipment" VALUES (5, 5, '9200252313991', '');
INSERT INTO "Equipment" VALUES (6, 3, '4457791543531', '');
INSERT INTO "Equipment" VALUES (7, 1, '1313596868138', '');
INSERT INTO "Equipment" VALUES (8, 6, '7597318412708', '');
INSERT INTO "Equipment" VALUES (9, 8, '4822292633102', '');
INSERT INTO "Equipment" VALUES (10, 8, '6928696723901', '');
INSERT INTO "Equipment" VALUES (11, 2, '9087530160153', '');
INSERT INTO "Equipment" VALUES (12, 7, '8156041618444', '');
INSERT INTO "Equipment" VALUES (13, 8, '6339115962717', '');
INSERT INTO "Equipment" VALUES (14, 6, '0239931969258', '');
INSERT INTO "Equipment" VALUES (15, 5, '7605596045249', '');
INSERT INTO "Equipment" VALUES (16, 6, '1321956525430', '');
INSERT INTO "Equipment" VALUES (17, 4, '7310667388148', '');
INSERT INTO "Equipment" VALUES (18, 7, '5412973340598', '');
INSERT INTO "Equipment" VALUES (19, 2, '5904086137092', '');
INSERT INTO "Equipment" VALUES (20, 2, '3143755868147', '');
INSERT INTO "Equipment" VALUES (21, 8, '7043091616982', '');
INSERT INTO "Equipment" VALUES (22, 4, '8977680662663', '');
INSERT INTO "Equipment" VALUES (23, 2, '7093982076906', '');
INSERT INTO "Equipment" VALUES (24, 3, '3005620372046', '');
INSERT INTO "Equipment" VALUES (25, 7, '0986708322357', '');
INSERT INTO "Equipment" VALUES (26, 5, '3879027954651', '');
INSERT INTO "Equipment" VALUES (27, 1, '6396350982436', '');
INSERT INTO "Equipment" VALUES (28, 8, '8160438444721', '');
INSERT INTO "Equipment" VALUES (29, 2, '1647803671328', '');
INSERT INTO "Equipment" VALUES (30, 4, '1530779227975', '');
INSERT INTO "Equipment" VALUES (31, 2, '7459687096371', '');
INSERT INTO "Equipment" VALUES (32, 8, '0696592306301', '');
INSERT INTO "Equipment" VALUES (33, 3, '5561083523862', '');
INSERT INTO "Equipment" VALUES (34, 1, '5021832255203', '');
INSERT INTO "Equipment" VALUES (35, 1, '7788337724167', '');
INSERT INTO "Equipment" VALUES (36, 2, '5297339846811', '');
INSERT INTO "Equipment" VALUES (37, 6, '6663537305655', '');
INSERT INTO "Equipment" VALUES (38, 3, '9531881398159', '');
INSERT INTO "Equipment" VALUES (39, 1, '9778005257590', '');
INSERT INTO "Equipment" VALUES (40, 8, '9497182259592', '');
INSERT INTO "Equipment" VALUES (41, 4, '7832125962412', '');
INSERT INTO "Equipment" VALUES (42, 6, '0255046378549', '');
INSERT INTO "Equipment" VALUES (43, 2, '2204600333980', '');
INSERT INTO "Equipment" VALUES (44, 3, '0511149076134', '');
INSERT INTO "Equipment" VALUES (45, 4, '1905685515315', '');
INSERT INTO "Equipment" VALUES (46, 5, '7838907236399', '');
INSERT INTO "Equipment" VALUES (47, 6, '5354962280679', '');
INSERT INTO "Equipment" VALUES (48, 5, '1278560664928', '');
INSERT INTO "Equipment" VALUES (49, 8, '2620475088747', '');
INSERT INTO "Equipment" VALUES (50, 2, '0982582070834', '');

INSERT INTO "Equipment Types" VALUES (1, 'Mountain Bike');
INSERT INTO "Equipment Types" VALUES (2, 'Road Bike');
INSERT INTO "Equipment Types" VALUES (3, 'Hybrid Bike');
INSERT INTO "Equipment Types" VALUES (4, 'Electric Bike');
INSERT INTO "Equipment Types" VALUES (5, 'BMX Bike');
INSERT INTO "Equipment Types" VALUES (6, 'Cyclocross Bike');
INSERT INTO "Equipment Types" VALUES (7, 'Folding Bike');
INSERT INTO "Equipment Types" VALUES (8, 'Touring Bike');

INSERT INTO "Mechanics" VALUES (1, 'Charles', 'Adkins');
INSERT INTO "Mechanics" VALUES (2, 'Robert', 'Thompson');
INSERT INTO "Mechanics" VALUES (3, 'Megan', 'Thomas');
INSERT INTO "Mechanics" VALUES (4, 'Matthew', 'Wheeler');
INSERT INTO "Mechanics" VALUES (5, 'Tracy', 'Charles');

INSERT INTO "Service Milestones" VALUES (1, 10, 2, '2025-01-07 08:47:46.217143', 'Frame: Noticed a crack near the bottom bracket; recommended a replacement.');
INSERT INTO "Service Milestones" VALUES (2, 10, 2, '2025-01-14 21:53:49.646056', 'Wheels: Customer pleased with how smooth the wheels now spin.');
INSERT INTO "Service Milestones" VALUES (3, 2, 2, '2025-01-16 03:49:19.193744', 'Seat: Replaced torn saddle with a new gel-padded seat.');
INSERT INTO "Service Milestones" VALUES (4, 11, 2, '2025-01-01 14:47:41.90018', 'Gears: Lubricated drivetrain; customer noticed quieter pedaling.');
INSERT INTO "Service Milestones" VALUES (5, 15, 3, '2025-01-03 20:15:51.170396', 'Handlebars: Handlebar alignment corrected; was slightly off-center.');
INSERT INTO "Service Milestones" VALUES (6, 17, 1, '2025-01-08 17:22:39.155486', 'Pedals: Upgraded pedals to a clipless system; customer very happy.');
INSERT INTO "Service Milestones" VALUES (7, 26, 1, '2025-01-10 10:38:02.995214', 'Brakes: Adjusted brake pads for better stopping power.');
INSERT INTO "Service Milestones" VALUES (8, 19, 4, '2025-01-09 04:36:45.996913', 'Brakes: Adjusted brake pads for better stopping power.');
INSERT INTO "Service Milestones" VALUES (9, 8, 4, '2025-01-08 18:23:47.468222', 'Brakes: Rear brake cable frayed; replaced with a new one.');
INSERT INTO "Service Milestones" VALUES (10, 26, 3, '2025-01-08 09:12:41.813921', 'Frame: Noticed a crack near the bottom bracket; recommended a replacement.');
INSERT INTO "Service Milestones" VALUES (11, 8, 2, '2025-01-08 20:10:16.393944', 'Brakes: Adjusted brake pads for better stopping power.');
INSERT INTO "Service Milestones" VALUES (12, 16, 2, '2025-01-12 10:50:06.55232', 'Seat: Customer commented that the saddle now feels like new.');
INSERT INTO "Service Milestones" VALUES (13, 30, 2, '2025-01-03 19:01:00.816007', 'Tires: Replaced a worn-out rear tire; customer opted for puncture-resistant model.');
INSERT INTO "Service Milestones" VALUES (14, 10, 2, '2025-01-15 07:55:45.629029', 'Tires: Customer appreciated advice on tire pressure for road biking.');
INSERT INTO "Service Milestones" VALUES (15, 30, 4, '2025-01-01 06:48:38.05714', 'Gears: Lubricated drivetrain; customer noticed quieter pedaling.');
INSERT INTO "Service Milestones" VALUES (16, 28, 1, '2025-01-03 04:44:26.454817', 'Pedals: Upgraded pedals to a clipless system; customer very happy.');
INSERT INTO "Service Milestones" VALUES (17, 18, 4, '2025-01-09 10:01:37.291468', 'Handlebars: Installed new ergonomic grips; customer was excited about the comfort.');
INSERT INTO "Service Milestones" VALUES (18, 6, 3, '2025-01-05 00:56:05.460386', 'Tires: Customer appreciated advice on tire pressure for road biking.');
INSERT INTO "Service Milestones" VALUES (19, 8, 1, '2025-01-16 16:12:54.908881', 'Brakes: Rear brake cable frayed; replaced with a new one.');
INSERT INTO "Service Milestones" VALUES (20, 22, 4, '2025-01-10 01:31:00.976382', 'Pedals: Upgraded pedals to a clipless system; customer very happy.');
INSERT INTO "Service Milestones" VALUES (21, 24, 1, '2025-01-13 01:57:55.013202', 'Frame: Frame cleaned and polished; customer commented on how shiny it looked.');
INSERT INTO "Service Milestones" VALUES (22, 6, 2, '2025-01-08 02:57:08.638848', 'Seat: Customer commented that the saddle now feels like new.');
INSERT INTO "Service Milestones" VALUES (23, 13, 2, '2025-01-08 11:12:10.861305', 'Brakes: Customer remarked how responsive the brakes feel now.');
INSERT INTO "Service Milestones" VALUES (24, 7, 1, '2025-01-03 23:27:02.387476', 'Pedals: Upgraded pedals to a clipless system; customer very happy.');
INSERT INTO "Service Milestones" VALUES (25, 12, 1, '2025-01-09 16:56:10.217908', 'Wheels: Replaced a broken spoke on the front wheel.');
INSERT INTO "Service Milestones" VALUES (26, 21, 1, '2025-01-01 20:13:06.888947', 'Frame: Noticed a crack near the bottom bracket; recommended a replacement.');
INSERT INTO "Service Milestones" VALUES (27, 18, 2, '2025-01-05 21:03:53.670845', 'Pedals: Mechanic noticed loose threads on right pedal spindle; tightened securely.');
INSERT INTO "Service Milestones" VALUES (28, 6, 4, '2025-01-10 02:57:38.500126', 'Seat: Replaced torn saddle with a new gel-padded seat.');
INSERT INTO "Service Milestones" VALUES (29, 21, 1, '2025-01-15 03:17:37.690491', 'Frame: Small dent on the top tube identified during inspection.');
INSERT INTO "Service Milestones" VALUES (30, 2, 1, '2025-01-06 17:35:00.879927', 'Handlebars: Installed new ergonomic grips; customer was excited about the comfort.');
INSERT INTO "Service Milestones" VALUES (31, 18, 1, '2025-01-07 18:13:48.771544', 'Pedals: Upgraded pedals to a clipless system; customer very happy.');
INSERT INTO "Service Milestones" VALUES (32, 18, 2, '2025-01-12 07:02:03.466806', 'Seat: Customer commented that the saddle now feels like new.');
INSERT INTO "Service Milestones" VALUES (33, 22, 2, '2025-01-02 22:43:37.408209', 'Frame: Small dent on the top tube identified during inspection.');
INSERT INTO "Service Milestones" VALUES (34, 10, 4, '2025-01-06 14:07:43.797434', 'Handlebars: Installed new ergonomic grips; customer was excited about the comfort.');
INSERT INTO "Service Milestones" VALUES (35, 1, 4, '2025-01-09 10:32:20.447052', 'Seat: Customer commented that the saddle now feels like new.');
INSERT INTO "Service Milestones" VALUES (36, 26, 2, '2025-01-03 04:55:00.043649', 'Handlebars: Installed new ergonomic grips; customer was excited about the comfort.');
INSERT INTO "Service Milestones" VALUES (37, 18, 2, '2025-01-04 03:00:33.453246', 'Gears: Customer reported skipping gears; adjusted indexing.');
INSERT INTO "Service Milestones" VALUES (38, 4, 1, '2025-01-12 02:49:09.994843', 'Frame: Small dent on the top tube identified during inspection.');
INSERT INTO "Service Milestones" VALUES (39, 8, 1, '2025-01-02 13:32:22.55004', 'Brakes: Rear brake cable frayed; replaced with a new one.');
INSERT INTO "Service Milestones" VALUES (40, 29, 3, '2025-01-01 14:47:35.608643', 'Brakes: Customer remarked how responsive the brakes feel now.');
INSERT INTO "Service Milestones" VALUES (41, 24, 1, '2025-01-12 19:07:40.671851', 'Handlebars: Handlebar alignment corrected; was slightly off-center.');
INSERT INTO "Service Milestones" VALUES (42, 5, 1, '2025-01-03 11:24:44.784795', 'Wheels: Replaced a broken spoke on the front wheel.');
INSERT INTO "Service Milestones" VALUES (43, 11, 2, '2025-01-07 09:07:49.404417', 'Brakes: Adjusted brake pads for better stopping power.');
INSERT INTO "Service Milestones" VALUES (44, 26, 2, '2025-01-05 23:07:49.298178', 'Brakes: Customer remarked how responsive the brakes feel now.');
INSERT INTO "Service Milestones" VALUES (45, 9, 2, '2025-01-04 07:33:35.602183', 'Tires: Customer appreciated advice on tire pressure for road biking.');
INSERT INTO "Service Milestones" VALUES (46, 18, 3, '2025-01-12 16:21:27.611156', 'Wheels: Bent rear rim; trued the wheel successfully.');
INSERT INTO "Service Milestones" VALUES (47, 5, 3, '2025-01-01 05:17:01.035835', 'Frame: Frame cleaned and polished; customer commented on how shiny it looked.');
INSERT INTO "Service Milestones" VALUES (48, 30, 4, '2025-01-12 23:37:54.705064', 'Wheels: Customer pleased with how smooth the wheels now spin.');
INSERT INTO "Service Milestones" VALUES (49, 29, 4, '2025-01-08 23:42:24.22679', 'Pedals: Upgraded pedals to a clipless system; customer very happy.');
INSERT INTO "Service Milestones" VALUES (50, 3, 1, '2025-01-14 04:23:15.225983', 'Pedals: Mechanic noticed loose threads on right pedal spindle; tightened securely.');
INSERT INTO "Service Milestones" VALUES (51, 10, 1, '2025-01-04 13:03:41.987045', 'Seat: Customer commented that the saddle now feels like new.');
INSERT INTO "Service Milestones" VALUES (52, 20, 2, '2025-01-08 20:16:51.693332', 'Pedals: Upgraded pedals to a clipless system; customer very happy.');
INSERT INTO "Service Milestones" VALUES (53, 30, 3, '2025-01-16 08:44:05.328637', 'Tires: Replaced a worn-out rear tire; customer opted for puncture-resistant model.');
INSERT INTO "Service Milestones" VALUES (54, 25, 4, '2025-01-07 22:58:50.430439', 'Brakes: Adjusted brake pads for better stopping power.');
INSERT INTO "Service Milestones" VALUES (55, 19, 1, '2025-01-12 03:34:01.011877', 'Pedals: Left pedal bearings replaced due to grinding noise.');
INSERT INTO "Service Milestones" VALUES (56, 6, 1, '2025-01-03 20:19:40.075034', 'Pedals: Left pedal bearings replaced due to grinding noise.');
INSERT INTO "Service Milestones" VALUES (57, 1, 3, '2025-01-15 11:55:15.440209', 'Wheels: Replaced a broken spoke on the front wheel.');
INSERT INTO "Service Milestones" VALUES (58, 14, 2, '2025-01-03 03:33:45.567633', 'Brakes: Customer remarked how responsive the brakes feel now.');
INSERT INTO "Service Milestones" VALUES (59, 3, 2, '2025-01-11 17:19:42.898977', 'Frame: Small dent on the top tube identified during inspection.');
INSERT INTO "Service Milestones" VALUES (60, 26, 1, '2025-01-06 19:15:00.420295', 'Brakes: Rear brake cable frayed; replaced with a new one.');
INSERT INTO "Service Milestones" VALUES (61, 13, 1, '2025-01-14 12:16:37.648064', 'Brakes: Adjusted brake pads for better stopping power.');
INSERT INTO "Service Milestones" VALUES (62, 1, 2, '2025-01-03 08:26:01.927882', 'Brakes: Customer remarked how responsive the brakes feel now.');
INSERT INTO "Service Milestones" VALUES (63, 29, 2, '2025-01-14 00:16:34.229102', 'Tires: Replaced a worn-out rear tire; customer opted for puncture-resistant model.');
INSERT INTO "Service Milestones" VALUES (64, 20, 4, '2025-01-10 21:03:09.608222', 'Handlebars: Re-wrapped handlebar tape; customer loved the color choice.');
INSERT INTO "Service Milestones" VALUES (65, 29, 4, '2025-01-07 07:00:07.904576', 'Handlebars: Installed new ergonomic grips; customer was excited about the comfort.');
INSERT INTO "Service Milestones" VALUES (66, 18, 1, '2025-01-02 10:05:24.98937', 'Wheels: Bent rear rim; trued the wheel successfully.');
INSERT INTO "Service Milestones" VALUES (67, 9, 4, '2025-01-02 05:23:49.940989', 'Brakes: Adjusted brake pads for better stopping power.');
INSERT INTO "Service Milestones" VALUES (68, 29, 1, '2025-01-05 12:44:50.590624', 'Brakes: Customer remarked how responsive the brakes feel now.');
INSERT INTO "Service Milestones" VALUES (69, 14, 1, '2025-01-08 13:34:34.01171', 'Pedals: Mechanic noticed loose threads on right pedal spindle; tightened securely.');
INSERT INTO "Service Milestones" VALUES (70, 16, 1, '2025-01-08 18:06:58.447946', 'Handlebars: Handlebar alignment corrected; was slightly off-center.');
INSERT INTO "Service Milestones" VALUES (71, 12, 4, '2025-01-06 01:12:12.590045', 'Handlebars: Installed new ergonomic grips; customer was excited about the comfort.');
INSERT INTO "Service Milestones" VALUES (72, 6, 1, '2025-01-07 15:06:05.361839', 'Frame: Small dent on the top tube identified during inspection.');
INSERT INTO "Service Milestones" VALUES (73, 3, 2, '2025-01-09 08:58:18.849503', 'Tires: Front tire inflated; slow leak detected and patched.');
INSERT INTO "Service Milestones" VALUES (74, 2, 4, '2025-01-11 23:16:55.910491', 'Pedals: Left pedal bearings replaced due to grinding noise.');
INSERT INTO "Service Milestones" VALUES (75, 13, 4, '2025-01-13 04:47:30.801282', 'Pedals: Upgraded pedals to a clipless system; customer very happy.');
INSERT INTO "Service Milestones" VALUES (76, 2, 1, '2025-01-09 13:41:58.636115', 'Tires: Replaced a worn-out rear tire; customer opted for puncture-resistant model.');
INSERT INTO "Service Milestones" VALUES (77, 29, 2, '2025-01-10 06:53:45.983297', 'Gears: Lubricated drivetrain; customer noticed quieter pedaling.');
INSERT INTO "Service Milestones" VALUES (78, 30, 2, '2025-01-07 12:32:40.057594', 'Brakes: Adjusted brake pads for better stopping power.');
INSERT INTO "Service Milestones" VALUES (79, 24, 4, '2025-01-07 15:44:32.816038', 'Wheels: Replaced a broken spoke on the front wheel.');
INSERT INTO "Service Milestones" VALUES (80, 12, 3, '2025-01-07 02:46:14.069672', 'Handlebars: Installed new ergonomic grips; customer was excited about the comfort.');
INSERT INTO "Service Milestones" VALUES (81, 17, 2, '2025-01-12 10:44:53.000051', 'Frame: Frame cleaned and polished; customer commented on how shiny it looked.');
INSERT INTO "Service Milestones" VALUES (82, 21, 1, '2025-01-05 12:32:51.917834', 'Brakes: Adjusted brake pads for better stopping power.');
INSERT INTO "Service Milestones" VALUES (83, 10, 2, '2025-01-09 23:35:26.263723', 'Frame: Noticed a crack near the bottom bracket; recommended a replacement.');
INSERT INTO "Service Milestones" VALUES (84, 3, 1, '2025-01-02 21:12:29.416106', 'Tires: Customer appreciated advice on tire pressure for road biking.');
INSERT INTO "Service Milestones" VALUES (85, 25, 4, '2025-01-15 21:36:30.448941', 'Gears: Shifted gears sticking; replaced derailleur hanger.');
INSERT INTO "Service Milestones" VALUES (86, 15, 2, '2025-01-14 18:45:36.484494', 'Wheels: Replaced a broken spoke on the front wheel.');
INSERT INTO "Service Milestones" VALUES (87, 22, 1, '2025-01-02 18:26:36.340023', 'Brakes: Adjusted brake pads for better stopping power.');
INSERT INTO "Service Milestones" VALUES (88, 21, 1, '2025-01-02 03:40:01.15845', 'Wheels: Replaced a broken spoke on the front wheel.');
INSERT INTO "Service Milestones" VALUES (89, 18, 3, '2025-01-15 18:18:53.681251', 'Gears: Customer reported skipping gears; adjusted indexing.');
INSERT INTO "Service Milestones" VALUES (90, 1, 2, '2025-01-02 03:17:35.638653', 'Handlebars: Handlebar alignment corrected; was slightly off-center.');
INSERT INTO "Service Milestones" VALUES (91, 24, 4, '2025-01-03 09:20:37.081151', 'Tires: Customer appreciated advice on tire pressure for road biking.');
INSERT INTO "Service Milestones" VALUES (92, 2, 2, '2025-01-08 13:35:06.177571', 'Handlebars: Installed new ergonomic grips; customer was excited about the comfort.');
INSERT INTO "Service Milestones" VALUES (93, 6, 4, '2025-01-06 19:12:43.223897', 'Frame: Frame cleaned and polished; customer commented on how shiny it looked.');
INSERT INTO "Service Milestones" VALUES (94, 28, 3, '2025-01-08 17:30:58.228861', 'Tires: Front tire inflated; slow leak detected and patched.');
INSERT INTO "Service Milestones" VALUES (95, 17, 3, '2025-01-09 11:28:29.178429', 'Brakes: Adjusted brake pads for better stopping power.');
INSERT INTO "Service Milestones" VALUES (96, 1, 3, '2025-01-02 05:15:28.978011', 'Frame: Noticed a crack near the bottom bracket; recommended a replacement.');
INSERT INTO "Service Milestones" VALUES (97, 2, 1, '2025-01-12 01:59:04.712426', 'Frame: Noticed a crack near the bottom bracket; recommended a replacement.');
INSERT INTO "Service Milestones" VALUES (98, 22, 4, '2025-01-12 22:50:53.99121', 'Tires: Front tire inflated; slow leak detected and patched.');
INSERT INTO "Service Milestones" VALUES (99, 3, 4, '2025-01-12 14:45:07.111919', 'Gears: Shifted gears sticking; replaced derailleur hanger.');
INSERT INTO "Service Milestones" VALUES (100, 29, 2, '2025-01-07 03:32:51.205724', 'Wheels: Replaced a broken spoke on the front wheel.');

INSERT INTO "Service Requests" VALUES (1, 10, 20, 2, 'Front fork feels stiff; possible suspension issue.', 458.1, '2025-01-05 10:11:28.768122', '2025-01-15 10:24:10.038635');
INSERT INTO "Service Requests" VALUES (2, 10, 48, 5, 'Front fork feels stiff; possible suspension issue.', 261.49, '2025-01-08 16:10:27.364208', '2025-01-15 17:25:56.997396');
INSERT INTO "Service Requests" VALUES (3, 16, 32, 2, 'Flat tire; needs replacement or repair.', 483.91, '2025-01-04 05:48:32.389068', NULL);
INSERT INTO "Service Requests" VALUES (4, 17, 17, 3, 'Chain keeps falling off during rides.', 453.96, '2025-01-08 03:27:45.85052', '2025-01-05 05:13:56.358573');
INSERT INTO "Service Requests" VALUES (5, 1, 32, 2, 'Flat tire; needs replacement or repair.', 103.24, '2025-01-10 02:20:00.766097', '2025-01-11 15:35:10.915119');
INSERT INTO "Service Requests" VALUES (6, 15, 18, 1, 'Electric bike battery isn''t holding charge.', 197.54, '2025-01-01 12:03:58.042472', NULL);
INSERT INTO "Service Requests" VALUES (7, 7, 3, 4, 'Bike makes a clicking noise while pedaling.', 233.9, '2025-01-13 11:20:58.417285', NULL);
INSERT INTO "Service Requests" VALUES (8, 2, 21, 3, 'Customer wants clipless pedals installed.', 485.6, '2025-01-09 13:27:47.273917', '2025-01-11 09:47:39.761001');
INSERT INTO "Service Requests" VALUES (9, 20, 8, 2, 'Bike makes a clicking noise while pedaling.', 81.49, '2025-01-06 19:51:24.391168', NULL);
INSERT INTO "Service Requests" VALUES (10, 3, 14, 5, 'Chain keeps falling off during rides.', 27.05, '2025-01-11 19:53:08.606539', NULL);
INSERT INTO "Service Requests" VALUES (11, 13, 18, 5, 'Gears are not shifting smoothly.', 481.54, '2025-01-09 06:56:16.379648', NULL);
INSERT INTO "Service Requests" VALUES (12, 2, 16, 4, 'Headset creaks when turning the handlebars.', 472.97, '2025-01-11 05:58:06.703393', NULL);
INSERT INTO "Service Requests" VALUES (13, 14, 10, 5, 'Customer wants clipless pedals installed.', 286.19, '2025-01-14 00:44:47.515397', '2025-01-01 10:35:45.207151');
INSERT INTO "Service Requests" VALUES (14, 11, 34, 1, 'Bike makes a clicking noise while pedaling.', 216.63, '2025-01-14 23:39:50.833382', '2025-01-14 00:24:09.762261');
INSERT INTO "Service Requests" VALUES (15, 10, 14, 2, 'Rear wheel wobbles; possible rim issue.', 231.79, '2025-01-06 20:24:41.615423', NULL);
INSERT INTO "Service Requests" VALUES (16, 5, 48, 2, 'Looking to upgrade to tubeless tires.', 469.17, '2025-01-15 16:32:01.041626', NULL);
INSERT INTO "Service Requests" VALUES (17, 5, 13, 3, 'Headset creaks when turning the handlebars.', 271.76, '2025-01-11 13:03:39.234821', NULL);
INSERT INTO "Service Requests" VALUES (18, 2, 8, 5, 'Flat tire; needs replacement or repair.', 336.89, '2025-01-02 20:24:57.577083', NULL);
INSERT INTO "Service Requests" VALUES (19, 2, 44, 1, 'Rear derailleur seems bent after a crash.', 234.89, '2025-01-01 04:41:49.123657', '2025-01-08 03:11:36.165671');
INSERT INTO "Service Requests" VALUES (20, 2, 2, 2, 'Handlebars feel loose and need adjustment.', 68.9, '2025-01-04 15:39:04.496455', '2025-01-09 15:19:04.966949');
INSERT INTO "Service Requests" VALUES (21, 7, 33, 3, 'Chain keeps falling off during rides.', 482.64, '2025-01-06 22:59:03.201623', '2025-01-04 11:08:54.975466');
INSERT INTO "Service Requests" VALUES (22, 2, 8, 2, 'Rear derailleur seems bent after a crash.', 294.89, '2025-01-03 03:16:14.928212', NULL);
INSERT INTO "Service Requests" VALUES (23, 7, 5, 3, 'Rear derailleur seems bent after a crash.', 93.91, '2025-01-06 11:17:17.671771', '2025-01-11 01:01:42.800117');
INSERT INTO "Service Requests" VALUES (24, 4, 18, 4, 'Brakes feel soft and don''t stop effectively.', 174.67, '2025-01-02 21:19:45.12961', '2025-01-07 07:31:27.930341');
INSERT INTO "Service Requests" VALUES (25, 12, 11, 5, 'Brakes feel soft and don''t stop effectively.', 430.31, '2025-01-12 01:24:57.391244', NULL);
INSERT INTO "Service Requests" VALUES (26, 19, 50, 2, 'Child seat needs to be installed securely on the frame.', 431.75, '2025-01-16 00:37:20.169067', NULL);
INSERT INTO "Service Requests" VALUES (27, 11, 27, 2, 'Customer wants clipless pedals installed.', 116.08, '2025-01-14 13:16:53.938555', NULL);
INSERT INTO "Service Requests" VALUES (28, 17, 37, 3, 'Electric bike battery isn''t holding charge.', 184.13, '2025-01-10 14:40:12.640842', NULL);
INSERT INTO "Service Requests" VALUES (29, 8, 44, 2, 'Child seat needs to be installed securely on the frame.', 166.73, '2025-01-06 21:30:57.229592', '2025-01-09 11:43:42.579269');
INSERT INTO "Service Requests" VALUES (30, 20, 33, 5, 'Customer wants help installing accessories (e.g., lights, rack).', 440.01, '2025-01-10 19:04:08.686107', NULL);

INSERT INTO "Service Statuses" VALUES (1, 'Received');
INSERT INTO "Service Statuses" VALUES (2, 'In Progress');
INSERT INTO "Service Statuses" VALUES (3, 'Awaiting Part');
INSERT INTO "Service Statuses" VALUES (4, 'Completed');

-- Reset sequences
SELECT pg_catalog.setval('"Customers_id_seq"', 20, true);
SELECT pg_catalog.setval('"Equipment Types_id_seq"', 8, true);
SELECT pg_catalog.setval('"Equipment_id_seq"', 50, true);
SELECT pg_catalog.setval('"Mechanics_id_seq"', 5, true);
SELECT pg_catalog.setval('"Service Milestones_id_seq"', 100, true);
SELECT pg_catalog.setval('"Service Requests_id_seq"', 30, true);
SELECT pg_catalog.setval('"Service Statuses_id_seq"', 4, true);

ALTER TABLE ONLY "Customers"
    ADD CONSTRAINT "Customers_pkey" PRIMARY KEY (id);

ALTER TABLE ONLY "Equipment Types"
    ADD CONSTRAINT "Equipment Types_pkey" PRIMARY KEY (id);

ALTER TABLE ONLY "Equipment"
    ADD CONSTRAINT "Equipment_pkey" PRIMARY KEY (id);

ALTER TABLE ONLY "Equipment"
    ADD CONSTRAINT "Equipment_serial_number_key" UNIQUE (serial_number);

ALTER TABLE ONLY "Mechanics"
    ADD CONSTRAINT "Mechanics_pkey" PRIMARY KEY (id);

ALTER TABLE ONLY "Service Milestones"
    ADD CONSTRAINT "Service Milestones_pkey" PRIMARY KEY (id);

ALTER TABLE ONLY "Service Requests"
    ADD CONSTRAINT "Service Requests_pkey" PRIMARY KEY (id);

ALTER TABLE ONLY "Service Statuses"
    ADD CONSTRAINT "Service Statuses_name_key" UNIQUE (name);

ALTER TABLE ONLY "Service Statuses"
    ADD CONSTRAINT "Service Statuses_pkey" PRIMARY KEY (id);

ALTER TABLE ONLY "Equipment"
    ADD CONSTRAINT "Equipment_type_id_fkey" FOREIGN KEY (type_id) REFERENCES "Equipment Types"(id);

ALTER TABLE ONLY "Service Milestones"
    ADD CONSTRAINT "Service Milestones_service_request_id_fkey" FOREIGN KEY (service_request_id) REFERENCES "Service Requests"(id);

ALTER TABLE ONLY "Service Milestones"
    ADD CONSTRAINT "Service Milestones_status_id_fkey" FOREIGN KEY (status_id) REFERENCES "Service Statuses"(id);

ALTER TABLE ONLY "Service Requests"
    ADD CONSTRAINT "Service Requests_customer_id_fkey" FOREIGN KEY (customer_id) REFERENCES "Customers"(id);

ALTER TABLE ONLY "Service Requests"
    ADD CONSTRAINT "Service Requests_equipment_id_fkey" FOREIGN KEY (equipment_id) REFERENCES "Equipment"(id);

ALTER TABLE ONLY "Service Requests"
    ADD CONSTRAINT "Service Requests_mechanic_id_fkey" FOREIGN KEY (mechanic_id) REFERENCES "Mechanics"(id);
