CREATE SCHEMA "Movie Collection";
SET search_path="Movie Collection";
-- Departments

CREATE TABLE "Departments" (
    id integer NOT NULL,
    "Name" text
);

ALTER TABLE "Departments" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Departments_id_seq"
);

-- Genres

CREATE TABLE "Genres" (
    id integer NOT NULL,
    "Name" text
);

ALTER TABLE "Genres" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Genres_id_seq"
);


-- Jobs

CREATE TABLE "Jobs" (
    id integer NOT NULL,
    "Name" text
);

ALTER TABLE "Jobs" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Jobs_id_seq"
);


-- Movie Cast Map

CREATE TABLE "Movie Cast Map" (
    id integer NOT NULL,
    "Character" text,
    "Movie" integer NOT NULL,
    "Cast Member" integer NOT NULL,
    "Credit Order" integer
);

ALTER TABLE "Movie Cast Map" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Movie Cast Map_id_seq"
);


-- Movie Crew Map

CREATE TABLE "Movie Crew Map" (
    id integer NOT NULL,
    "Job" integer,
    "Department" integer,
    "Movie" integer NOT NULL,
    "Crew Member" integer NOT NULL
);

ALTER TABLE "Movie Crew Map" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Movie Crew Map_id_seq"
);


-- Movie Genre Map

CREATE TABLE "Movie Genre Map" (
    id integer NOT NULL,
    "Movie" integer,
    "Genre" integer
);

ALTER TABLE "Movie Genre Map" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Movie Genre Map_id_seq"
);


-- Movie Production Company Map

CREATE TABLE "Movie Production Company Map" (
    id integer NOT NULL,
    "Movie" integer,
    "Production Company" integer
);

ALTER TABLE "Movie Production Company Map" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Movie Production Company Map_id_seq"
);


-- Movie Production Country Map

CREATE TABLE "Movie Production Country Map" (
    id integer NOT NULL,
    "Movie" integer NOT NULL,
    "Production Country" integer NOT NULL
);

ALTER TABLE "Movie Production Country Map" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Movie Production Country Map_id_seq"
);


-- Movie Spoken Language Map

CREATE TABLE "Movie Spoken Language Map" (
    id integer NOT NULL,
    "Movie" integer NOT NULL,
    "Spoken Language" integer NOT NULL
);

ALTER TABLE "Movie Spoken Language Map" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Movie Spoken Language Map_id_seq"
);


-- Movies

CREATE TABLE "Movies" (
    id integer NOT NULL,
    "Title" text,
    "Release Date" date,
    "Runtime" numeric,
    "Homepage" mathesar_types.uri,
    "Sub-Collection" integer,
    "Imdb ID" text,
    "Tagline" text,
    "Overview" text,
    "Budget" mathesar_types.mathesar_money,
    "Revenue" mathesar_types.mathesar_money,
    "Original Title" text,
    "Original Language" text
);

ALTER TABLE "Movies" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Movies_id_seq"
);


-- People

CREATE TABLE "People" (
    id integer NOT NULL,
    "Name" text
);

ALTER TABLE "People" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "People_id_seq"
);


-- Production Companies

CREATE TABLE "Production Companies" (
    id integer NOT NULL,
    "Name" text
);

ALTER TABLE "Production Companies" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Production Companies_id_seq"
);


-- Production Countries

CREATE TABLE "Production Countries" (
    id integer NOT NULL,
    "Name" text NOT NULL,
    "ISO 3166-1" character(2) NOT NULL
);

ALTER TABLE "Production Countries" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Production Countries_id_seq"
);


-- Spoken Languages

CREATE TABLE "Spoken Languages" (
    id integer NOT NULL,
    "Name" text,
    "ISO 639-1" character(2) NOT NULL
);

ALTER TABLE "Spoken Languages" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Spoken Languages_id_seq"
);


-- Sub-Collections

CREATE TABLE "Sub-Collections" (
    id integer NOT NULL,
    "Name" text
);

ALTER TABLE "Sub-Collections" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Sub-Collections_id_seq"
);
