<script lang="ts">
  import { _ } from 'svelte-i18n';

  import type { FileManifest } from '@mathesar/api/rpc/records';
  import { assertExhaustive } from '@mathesar/component-library';
  import ContentLoading from '@mathesar/components/ContentLoading.svelte';
  import { toast } from '@mathesar/stores/toast';

  import { fetchImage, getFileViewerType } from '../fileUtils';

  export let manifest: FileManifest;
  export let canOpenViewer: boolean;
  export let openImageFileViewer: (p: {
    imageElement: HTMLImageElement;
    zoomOrigin?: DOMRect;
  }) => void;

  /**
   * This controls the pixel dimensions of the fetched thumbnail size, as
   * generated by the service layer. It does not control the visual size of the
   * thumbnail.
   */
  export let thumbnailResolutionHeightPx: number;

  let thumbnailElement: HTMLImageElement;
  let imageLoading = false;
  let imageElement: HTMLImageElement | undefined;

  $: ({ uri, thumbnail, direct } = manifest);
  $: fileViewerType = getFileViewerType(manifest);
  $: thumbnailUrl = `${thumbnail}?height=${thumbnailResolutionHeightPx}`;

  async function loadImage() {
    imageLoading = true;
    imageElement = await fetchImage(direct);
    imageLoading = false;
  }

  async function handleImgClick() {
    // TODO_FILES_UI: Fix click behavior. Clicking on the thumbnail of an
    // inactive cell should _not_ open the file viewer.
    if (!canOpenViewer) return;

    if (!imageElement) {
      await loadImage();
      // TODO_FILES_UI consider click listener on window to stop lightbox from
      // opening while image is fetching?
    }

    if (!imageElement) {
      toast.error($_('failed_to_load_image'));
      return;
    }

    openImageFileViewer({
      imageElement,
      zoomOrigin: thumbnailElement.getBoundingClientRect(),
    });
  }
</script>

<div class="file-cell-content">
  <div class="attached-file" class:can-open={canOpenViewer}>
    {#if fileViewerType === 'image'}
      <div class="image">
        <ContentLoading loading={imageLoading}>
          <img
            alt={uri}
            src={thumbnailUrl}
            on:click={handleImgClick}
            bind:this={thumbnailElement}
          />
        </ContentLoading>
      </div>
    {:else if fileViewerType === 'default'}
      <!-- TODO_FILES_UI: Improve this display. Use a generic icon + file name -->
      {uri}
    {:else}
      {assertExhaustive(fileViewerType)}
    {/if}
  </div>
</div>

<style lang="scss">
  .file-cell-content {
    display: grid;
    overflow: hidden;
    height: 100%;
  }

  .attached-file {
    height: 100%;
    overflow: hidden;
    display: flex;
  }

  .image {
    height: 100%;
    --ContentLoading__height: 100%;
    img {
      display: block;
      height: 100%;
    }
  }

  .attached-file.can-open .image {
    cursor: pointer;
  }
</style>
