<script lang="ts">
  import { _ } from 'svelte-i18n';

  import type { FileManifest } from '@mathesar/api/rpc/records';
  import {
    Icon,
    assertExhaustive,
    iconFileAlt,
    iconPDF,
  } from '@mathesar/component-library';
  import Button from '@mathesar/component-library/button/Button.svelte';
  import Spinner from '@mathesar/component-library/spinner/Spinner.svelte';
  import Tooltip from '@mathesar/component-library/tooltip/Tooltip.svelte';
  import { toast } from '@mathesar/stores/toast';

  import { fetchImage, getFileName, getFileViewerType } from '../fileUtils';

  export let manifest: FileManifest;
  export let canOpenViewer: boolean;
  export let openImageFileViewer: (p: {
    imageElement: HTMLImageElement;
    zoomOrigin?: DOMRect;
  }) => void;

  /**
   * This controls the pixel dimensions of the fetched thumbnail size, as
   * generated by the service layer. It does not control the visual size of the
   * thumbnail.
   */
  export let thumbnailResolutionHeightPx: number;

  let thumbnailElement: HTMLImageElement;
  let imageLoading = false;
  let imageElement: HTMLImageElement | undefined;

  $: ({ uri, thumbnail, direct, mimetype } = manifest);
  $: fileViewerType = getFileViewerType(manifest);
  $: thumbnailUrl = `${thumbnail}?height=${thumbnailResolutionHeightPx}`;
  $: fileName = getFileName(manifest);
  // TODO_FILES_UI: Support a wider range of filetype icons and use a
  // more robust solution to map mime types to icons.
  $: fileIcon = mimetype === 'application/pdf' ? iconPDF : iconFileAlt;

  async function loadImage() {
    imageLoading = true;
    imageElement = await fetchImage(direct);
    imageLoading = false;
  }

  async function handleImgClick() {
    // TODO_FILES_UI: Fix click behavior. Clicking on the thumbnail of an
    // inactive cell should _not_ open the file viewer.
    if (!canOpenViewer) return;

    if (!imageElement) {
      await loadImage();
      // TODO_FILES_UI consider click listener on window to stop lightbox from
      // opening while image is fetching?
    }

    if (!imageElement) {
      toast.error($_('failed_to_load_image'));
      return;
    }

    openImageFileViewer({
      imageElement,
      zoomOrigin: thumbnailElement.getBoundingClientRect(),
    });
  }
</script>

<div class="file-cell-content">
  <div class="attached-file" class:can-open={canOpenViewer}>
    {#if fileViewerType === 'image'}
      <!-- TODO_FILES_UI: add a loading indicator when thumbnail is loading -->
      <!-- TODO_FILES_UI: Fix hover behavior. Hovering the thumbnail of an
        inactive cell should _not_ open the tooltip. -->
      <Tooltip>
        <svelte:fragment slot="content">{fileName}</svelte:fragment>
        <img
          slot="trigger"
          alt={uri}
          src={thumbnailUrl}
          on:click={handleImgClick}
          bind:this={thumbnailElement}
        />
      </Tooltip>
      {#if imageLoading}
        <!-- TODO_FILES_UI: Display spinner over thumbnail somehow -->
        <Spinner />
      {/if}
    {:else if fileViewerType === 'default'}
      <Button aria-label={uri} appearance="secondary" tooltip={fileName}>
        <Icon {...fileIcon} />
      </Button>
    {:else}
      {assertExhaustive(fileViewerType)}
    {/if}
  </div>
</div>

<style>
  .file-cell-content {
    display: grid;
    overflow: hidden;
    height: 100%;
  }

  .attached-file {
    height: 100%;
    overflow: hidden;
    display: flex;
    padding: 0.1em;
  }

  img {
    display: block;
    height: 100%;
    width: auto;
    border: solid 1px var(--color-border-input);
    border-radius: var(--border-radius-m);
  }

  .attached-file.can-open img {
    cursor: pointer;
  }
</style>
