<script lang="ts">
  import type { FileManifest } from '@mathesar/api/rpc/records';
  import Default from '@mathesar/components/Default.svelte';
  import { iconAddNew } from '@mathesar/icons';
  import type { MessageReceiver } from '@mathesar/utils/OneWayMessageChannel';
  import { Button, Icon } from '@mathesar-component-library';

  import { lightboxContext } from '../lightbox/LightboxController';

  const lightbox = lightboxContext.get();

  export let value: unknown = undefined;
  export let manifest: FileManifest;
  export let canOpenViewer: boolean;
  export let onParentTriggersFileViewer: MessageReceiver;
  export let updateCell: (v: unknown) => void;
  /**
   * This controls the pixel dimensions of the fetched thumbnail size, as
   * generated by the service layer. It does not control the visual size of the
   * thumbnail.
   */
  export let thumbnailResolutionHeightPx: number;
  export let canUpload: boolean;

  $: hasValue = value !== undefined && value !== null;

  $: ({ mimetype, uri, thumbnail } = manifest);
  $: mimeCategory = mimetype.split('/').at(0) ?? 'unknown';
  $: thumbnailUrl = `${thumbnail}?height=${thumbnailResolutionHeightPx}`;

  function openFileViewer() {
    // TODO_FILES_UI: Fix click behavior. Clicking on the thumbnail of an
    // inactive cell should _not_ open the file viewer.

    if (!manifest) return;
    if (!canOpenViewer) return;
    if (!lightbox) return;
    lightbox.open(manifest, { removeFile: () => updateCell(null) });
  }

  function upload() {
    // TODO_FILES_UI
  }

  onParentTriggersFileViewer(openFileViewer);
</script>

<div class="file-cell-content">
  {#if hasValue}
    {#if manifest}
      <div class="attached-file" class:can-open={canOpenViewer}>
        {#if mimeCategory === 'image'}
          <!-- TODO_FILES_UI: add a loading indicator -->
          <img alt={uri} src={thumbnailUrl} on:click={openFileViewer} />
        {:else}
          <!-- TODO_FILES_UI: we probably want to display a generic icon here instead -->
          {uri}
        {/if}
      </div>
    {:else}
      {value}
    {/if}
  {:else if value === undefined}
    <div class="centered">
      <Default />
    </div>
  {:else}
    <div class="add">
      {#if canUpload}
        <Button on:click={upload}>
          <Icon {...iconAddNew} />
        </Button>
      {/if}
    </div>
  {/if}
</div>

<style>
  .file-cell-content {
    display: grid;
    overflow: hidden;
    height: 100%;
  }
  .centered {
    display: grid;
    align-items: center;
    justify-content: start;
    padding-inline: var(--cell-padding);
  }
  .add {
    display: grid;
    align-items: center;
    justify-content: end;
    padding-inline: var(--cell-padding);
  }

  .attached-file {
    height: 100%;
    overflow: hidden;
  }
  img {
    display: block;
    height: 100%;
    width: auto;
  }
  .attached-file.can-open img {
    cursor: pointer;
  }
</style>
