CREATE TABLE "Payments" (
  id integer NOT NULL,
  "Payment Mode" text,
  "Is Fraudulent" boolean
);

CREATE SEQUENCE "Payments_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE "Payments_id_seq" OWNED BY "Payments".id;

ALTER TABLE ONLY "Payments" ALTER COLUMN id SET DEFAULT nextval('"Payments_id_seq"'::regclass);

INSERT INTO "Payments" (id, "Payment Mode", "Is Fraudulent") VALUES
(1, 'credit card', false),
(2, 'debit card', false),
(3, 'wallet', true),
(4, 'UPI', false),
(5, 'credit card', false),
(6, 'wallet', true),
(7, 'debit card', false),
(8, 'pay later', false),
(9, 'debit card', false),
(10, 'debit card', false),
(11, 'pay later', false),
(12, 'debit card', false),
(13, 'wallet', true),
(14, 'wallet', false),
(15, 'UPI', true),
(16, 'credit card', false),
(17, 'wallet', false),
(18, 'debit card', false),
(19, 'debit card', false),
(20, 'credit card', false),
(21, 'debit card', true),
(22, 'credit card', false),
(23, 'debit card', false),
(24, 'debit card', false),
(25, 'wallet', false),
(26, 'wallet', false),
(27, 'wallet', false),
(28, 'wallet', false),
(29, 'credit card', false),
(30, 'wallet', false),
(31, 'wallet', false),
(32, 'debit card', false),
(33, 'debit card', false),
(34, 'debit card', false),
(35, 'pay later', false),
(36, 'debit card', false),
(37, 'wallet', false),
(38, 'debit card', true),
(39, 'credit card', false),
(40, 'UPI', false),
(41, 'debit card', false),
(42, 'credit card', false),
(43, 'credit card', false),
(44, 'wallet', false),
(45, 'pay later', false),
(46, 'credit card', true),
(47, 'debit card', false),
(48, 'credit card', false),
(49, 'wallet', false),
(50, 'UPI', false),
(51, 'debit card', false),
(52, 'debit card', false),
(53, 'wallet', false),
(54, 'debit card', false),
(55, 'credit card', false),
(56, 'pay later', false),
(57, 'debit card', true),
(58, 'wallet', false),
(59, 'credit card', false),
(60, 'debit card', false),
(61, 'wallet', true),
(62, 'wallet', false),
(63, 'debit card', false),
(64, 'credit card', false),
(65, 'wallet', false),
(66, 'debit card', false),
(67, 'debit card', false),
(68, 'pay later', true),
(69, 'debit card', false),
(70, 'debit card', false),
(71, 'wallet', false),
(72, 'wallet', false),
(73, 'credit card', false),
(74, 'debit card', false),
(75, 'UPI', false),
(76, 'debit card', false),
(77, 'wallet', false),
(78, 'credit card', true),
(79, 'wallet', true),
(80, 'debit card', false),
(81, 'debit card', false),
(82, 'credit card', false),
(83, 'debit card', false),
(84, 'wallet', false),
(85, 'wallet', true),
(86, 'UPI', false),
(87, 'credit card', false),
(88, 'wallet', false),
(89, 'debit card', false),
(90, 'debit card', false),
(91, 'credit card', false),
(92, 'pay later', false),
(93, 'debit card', false),
(94, 'wallet', false),
(95, 'debit card', true),
(96, 'debit card', false),
(97, 'wallet', false),
(98, 'wallet', false),
(99, 'credit card', false),
(100, 'wallet', true);

SELECT pg_catalog.setval('"Payments_id_seq"', 100, true);

ALTER TABLE ONLY "Payments"
    ADD CONSTRAINT "Payments_pkey" PRIMARY KEY (id);