COLUMN_NAME_TEMPLATE = 'Column '  # auto generated column name 'Column 1' (no undescore)

MATHESAR_PREFIX = "mathesar_"
MSAR_PUBLIC_SCHEMA = 'msar'
MSAR_PRIVATE_SCHEMA = f"__{MSAR_PUBLIC_SCHEMA}"
TYPES_SCHEMA = f"{MATHESAR_PREFIX}types"

INTERNAL_SCHEMAS = {
    TYPES_SCHEMA,
    MSAR_PUBLIC_SCHEMA,
    MSAR_PRIVATE_SCHEMA,
}
