# Generated by Django 3.1.7 on 2021-04-21 12:52

from django.db import migrations
from django.conf import settings
from db import install


def create_mathesar_db(apps, schema_editor):
    install.create_mathesar_database(
        settings.DATABASES["mathesar_tables"]["NAME"],
        settings.DATABASES["default"]["USER"],
        settings.DATABASES["default"]["PASSWORD"],
        settings.DATABASES["default"]["HOST"],
        settings.DATABASES["default"]["NAME"],
        settings.DATABASES["default"]["PORT"],
    )


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0001_initial'),
    ]
    operations = [
        migrations.RunPython(create_mathesar_db)
    ]
