# Generated by Django 3.1.14 on 2022-10-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='column',
            name='unique_column',
        ),
        migrations.AddConstraint(
            model_name='column',
            constraint=models.UniqueConstraint(fields=('attnum', 'table'), name='unique_column'),
        ),
    ]
