# Generated by Django 3.1.14 on 2022-07-19 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='import_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mathesar.table'),
        ),
        migrations.AddField(
            model_name='table',
            name='is_temp',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
