# Generated by Django 3.1.14 on 2023-05-31 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='type',
            field=models.CharField(choices=[('CSV', 'Csv'), ('TSV', 'Tsv'), ('JSON', 'Json')], default='CSV', max_length=128),
            preserve_default=False,
        ),
    ]
