# Generated by Django 3.1.14 on 2022-07-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='import_target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='is_temp',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
