# Generated by Django 4.2.18 on 2025-02-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0002_custom_db_server_integrity_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnmetadata',
            name='display_width',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
