# Generated by Django 4.2.18 on 2025-02-12 07:40

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0002_custom_db_server_integrity_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuredrole',
            name='password',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
    ]
