# Generated by Django 3.1.14 on 2022-08-03 16:37

from django.db import migrations, models
import mathesar.models.query


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0002_auto_20220719_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uiquery',
            name='display_options',
            field=models.JSONField(blank=True, null=True, validators=[mathesar.models.query._validate_dict]),
        ),
        migrations.AlterField(
            model_name='uiquery',
            name='initial_columns',
            field=models.JSONField(blank=True, null=True, validators=[mathesar.models.query._validate_list_of_dicts, mathesar.models.query._validate_initial_columns]),
        ),
        migrations.AlterField(
            model_name='uiquery',
            name='transformations',
            field=models.JSONField(blank=True, null=True, validators=[mathesar.models.query._validate_list_of_dicts, mathesar.models.query._validate_transformations]),
        ),
    ]
