# Generated by Django 4.2.17 on 2025-02-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0002_custom_db_server_integrity_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='nickname',
            field=models.CharField(null=True),
        ),
    ]
