# Generated by Django 3.1.14 on 2022-10-06 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0002_auto_20221006_2232'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='constraint',
            constraint=models.UniqueConstraint(fields=('oid', 'table'), name='unique_constraint'),
        ),
    ]
