# Generated by Django 3.1.7 on 2021-06-04 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0002_auto_20210521_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafile',
            name='schema',
        ),
        migrations.RemoveField(
            model_name='datafile',
            name='table_imported_to',
        ),
        migrations.AddField(
            model_name='table',
            name='data_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='mathesar.datafile'),
        ),
    ]
