# Generated by Django 3.1.14 on 2023-07-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0002_datafile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='max_level',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
