# Generated by Django 3.1.7 on 2021-06-04 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0003_auto_20210604_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='data_file',
        ),
        migrations.AddField(
            model_name='datafile',
            name='table_imported_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_files', to='mathesar.table'),
        ),
    ]
