# Generated by Django 3.1.14 on 2022-09-23 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0003_auto_20220803_1637'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='column',
            name='unique_column',
        ),
        migrations.AlterField(
            model_name='uiquery',
            name='base_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='mathesar.table'),
        ),
        migrations.AddConstraint(
            model_name='column',
            constraint=models.UniqueConstraint(fields=('attnum', 'table'), name='unique_column'),
        ),
    ]
