# Generated by Django 3.1.14 on 2022-09-27 06:57

from django.db import migrations, models
import django.db.models.deletion
import mathesar.models.query


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0003_auto_20220803_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uiquery',
            name='base_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='mathesar.table'),
        ),
        migrations.AlterField(
            model_name='uiquery',
            name='initial_columns',
            field=models.JSONField(validators=[mathesar.models.query._validate_list_of_dicts, mathesar.models.query._validate_initial_columns]),
        ),
    ]
