# Generated by Django 3.1.14 on 2023-07-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0003_datafile_max_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(blank=True, default='en', max_length=30),
        ),
    ]
