# Generated by Django 3.1.14 on 2022-10-09 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0003_auto_20221006_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('editor', 'Editor'), ('viewer', 'Viewer')], max_length=10)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathesar.schema')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schema_roles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('editor', 'Editor'), ('viewer', 'Viewer')], max_length=10)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathesar.database')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='database_roles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='schemarole',
            constraint=models.UniqueConstraint(fields=('user', 'schema'), name='unique_schema_role'),
        ),
        migrations.AddConstraint(
            model_name='databaserole',
            constraint=models.UniqueConstraint(fields=('user', 'database'), name='unique_database_role'),
        ),
    ]
