# Generated by Django 4.2.18 on 2025-03-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0003_v021'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablemetadata',
            name='mathesar_added_pkey_attnum',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
