# Generated by Django 3.1.14 on 2023-09-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0004_shares'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_language',
            field=models.CharField(blank=True, default='en', max_length=30),
        ),
    ]
