# Generated by Django 3.1.14 on 2023-11-04 10:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0004_shares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constraint',
            name='oid',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='schema',
            name='oid',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='oid',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tablesettings',
            name='column_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), default=None, null=True, size=None),
        ),
    ]
