# Generated by Django 3.1.7 on 2021-06-14 21:37

from django.db import migrations, models
import mathesar.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0004_auto_20210604_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='delimiter',
            field=models.CharField(default=',', max_length=1),
        ),
        migrations.AddField(
            model_name='datafile',
            name='escapechar',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='datafile',
            name='quotechar',
            field=models.CharField(default='"', max_length=1),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='file',
            field=models.FileField(upload_to=mathesar.utils.models.user_directory_path),
        ),
    ]
