# Generated by Django 3.1.14 on 2023-08-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0004_shares'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='db_host',
            field=models.CharField(default='mathesar_dev_db', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='database',
            name='db_password',
            field=models.CharField(default='mathesar', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='database',
            name='db_port',
            field=models.IntegerField(default=5432),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='database',
            name='db_username',
            field=models.CharField(default='mathesar', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='database',
            name='editable',
            field=models.BooleanField(default=True),
        ),
    ]
