# Generated by Django 3.1.14 on 2022-09-29 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0004_auto_20220923_0036'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='constraint',
            constraint=models.UniqueConstraint(fields=('oid', 'table'), name='unique_constraint'),
        ),
    ]
