# Generated by Django 3.1.14 on 2023-08-28 14:40

from django.db import migrations, models
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0004_shares'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='db_host',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='database',
            name='db_password',
            field=encrypted_fields.fields.EncryptedCharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='database',
            name='db_port',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='database',
            name='db_username',
            field=encrypted_fields.fields.EncryptedCharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='database',
            name='editable',
            field=models.BooleanField(default=True),
        ),
    ]
