# Generated by Django 4.2.22 on 2025-07-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0005_make_server_port_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsreport',
            name='sso_connected_user_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
