# Generated by Django 4.2.22 on 2025-06-23 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0005_make_server_port_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(unique=True)),
                ('name', models.CharField()),
                ('description', models.CharField(null=True)),
                ('version', models.IntegerField()),
                ('schema_oid', models.PositiveBigIntegerField()),
                ('base_table_oid', models.PositiveBigIntegerField()),
                ('is_public', models.BooleanField(default=False)),
                ('header_title', models.JSONField()),
                ('header_subtitle', models.JSONField(null=True)),
                ('submit_message', models.JSONField(null=True)),
                ('redirect_url', models.URLField(null=True)),
                ('submit_label', models.CharField(null=True)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathesar.database')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathesar.server')),
                ('submit_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mathesar.configuredrole')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField()),
                ('attnum', models.SmallIntegerField()),
                ('index', models.IntegerField()),
                ('kind', models.CharField(choices=[('scalar_column', 'scalar_column'), ('foreign_key', 'foreign_key'), ('reverse_foreign_key', 'reverse_foreign_key')])),
                ('label', models.CharField(null=True)),
                ('help', models.CharField(null=True)),
                ('readonly', models.BooleanField(default=False)),
                ('styling', models.JSONField(null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('target_table_oid', models.PositiveBigIntegerField(null=True)),
                ('allow_create', models.BooleanField(default=False)),
                ('create_label', models.CharField(null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='mathesar.form')),
                ('parent_field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_fields', to='mathesar.formfield')),
            ],
        ),
        migrations.AddConstraint(
            model_name='formfield',
            constraint=models.UniqueConstraint(fields=('key', 'form'), name='unique_key_per_form'),
        ),
    ]
