# Generated by Django 4.2.21 on 2025-06-30 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0005_make_server_port_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(unique=True)),
                ('name', models.CharField()),
                ('description', models.CharField(null=True)),
                ('version', models.PositiveSmallIntegerField()),
                ('schema_oid', models.PositiveBigIntegerField()),
                ('base_table_oid', models.PositiveBigIntegerField()),
                ('header_title', models.JSONField()),
                ('header_subtitle', models.JSONField(null=True)),
                ('share_public', models.BooleanField(default=False)),
                ('submit_message', models.JSONField(null=True)),
                ('submit_redirect_url', models.URLField(null=True)),
                ('submit_button_label', models.CharField(null=True)),
                ('associated_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mathesar.configuredrole')),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathesar.database')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathesar.server')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=128)),
                ('index', models.PositiveIntegerField()),
                ('label', models.CharField(null=True)),
                ('help', models.CharField(null=True)),
                ('kind', models.CharField(choices=[('scalar_column', 'Scalar column'), ('foreign_key', 'Foreign key'), ('reverse_foreign_key', 'Reverse foreign key')])),
                ('column_attnum', models.SmallIntegerField(null=True)),
                ('constraint_oid', models.PositiveBigIntegerField(null=True)),
                ('related_table_oid', models.PositiveBigIntegerField(null=True)),
                ('styling', models.JSONField(null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='mathesar.form')),
                ('parent_field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_fields', to='mathesar.formfield')),
            ],
        ),
        migrations.AddConstraint(
            model_name='formfield',
            constraint=models.UniqueConstraint(fields=('key', 'form'), name='form_field_unique_key_per_form'),
        ),
        migrations.AddConstraint(
            model_name='formfield',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('kind', 'scalar_column'), _negated=True), ('column_attnum__isnull', False), _connector='OR'), name='form_field_scalar_requirements'),
        ),
        migrations.AddConstraint(
            model_name='formfield',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('kind', 'foreign_key'), _negated=True), models.Q(('column_attnum__isnull', False), ('constraint_oid__isnull', False), ('related_table_oid__isnull', False)), _connector='OR'), name='form_field_foreign_key_requirements'),
        ),
        migrations.AddConstraint(
            model_name='formfield',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('kind', 'reverse_foreign_key'), _negated=True), models.Q(('constraint_oid__isnull', False), ('related_table_oid__isnull', False)), _connector='OR'), name='form_field_reverse_foreign_key_requirements'),
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE mathesar_form
            ADD CONSTRAINT form_database_server_integrity
              FOREIGN KEY (database_id, server_id)
              REFERENCES mathesar_database(id, server_id);
            """,
            reverse_sql="""
            ALTER TABLE mathesar_form
            DROP CONSTRAINT form_database_server_integrity;
            """
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE mathesar_form
            ADD CONSTRAINT form_role_server_integrity
              FOREIGN KEY (associated_role_id, server_id)
              REFERENCES mathesar_configuredrole(id, server_id);
            """,
            reverse_sql="""
            ALTER TABLE mathesar_form
            DROP CONSTRAINT form_role_server_integrity;
            """
        ),
    ]
