# Generated by Django 3.1.14 on 2023-09-06 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0005_datafile_sheet_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafile',
            name='sheet_name',
        ),
        migrations.AddField(
            model_name='datafile',
            name='sheet_index',
            field=models.IntegerField(default=0),
        ),
    ]
