# Generated by Django 4.2.21 on 2025-06-02 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0005_make_server_port_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('version', models.IntegerField()),
                ('base_table_oid', models.PositiveBigIntegerField()),
                ('schema_oid', models.PositiveBigIntegerField()),
                ('description', models.CharField(null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathesar.database')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField()),
                ('subtitle', models.CharField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubmissionSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(null=True)),
                ('redirect_url', models.URLField(null=True)),
                ('submit_label', models.CharField(null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathesar.configuredrole')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('attnum', models.SmallIntegerField()),
                ('table_oid', models.PositiveBigIntegerField()),
                ('kind', models.CharField(choices=[('scalar_column', 'scalar_column'), ('foreign_key', 'foreign_key'), ('reverse_foreign_key', 'reverse_foreign_key')])),
                ('record_summary_template', models.JSONField(null=True)),
                ('label', models.CharField(null=True)),
                ('help', models.CharField(null=True)),
                ('placeholder', models.CharField(null=True)),
                ('needs_validation', models.BooleanField(default=False)),
                ('readonly', models.BooleanField(default=False)),
                ('styling', models.JSONField(null=True)),
                ('related_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_field', to='mathesar.form')),
            ],
        ),
        migrations.AddField(
            model_name='form',
            name='header',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='mathesar.formheader'),
        ),
        migrations.AddField(
            model_name='form',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathesar.submissionsettings'),
        ),
        migrations.AddConstraint(
            model_name='formfield',
            constraint=models.UniqueConstraint(fields=('attnum', 'table_oid', 'related_form'), name='unique_attnum_table_oid_form'),
        ),
    ]
