# Generated by Django 3.1.14 on 2024-01-30 07:21

from django.db import migrations, models
import mathesar.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0005_release_0_1_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='version',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='tablesettings',
            name='column_order',
            field=models.JSONField(blank=True, default=None, null=True, validators=[mathesar.models.base.validate_column_order]),
        ),
    ]
