# Generated by Django 4.2.22 on 2025-07-18 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0006_analyticsreport_sso_connected_user_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(unique=True)),
                ('name', models.CharField()),
                ('description', models.CharField(null=True)),
                ('version', models.PositiveSmallIntegerField()),
                ('schema_oid', models.PositiveBigIntegerField()),
                ('base_table_oid', models.PositiveBigIntegerField()),
                ('header_title', models.JSONField()),
                ('header_subtitle', models.JSONField(null=True)),
                ('publish_public', models.BooleanField(default=False)),
                ('submit_message', models.JSONField(null=True)),
                ('submit_redirect_url', models.URLField(null=True)),
                ('submit_button_label', models.CharField(null=True)),
                ('associated_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mathesar.configuredrole')),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathesar.database')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathesar.server')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=128)),
                ('index', models.PositiveIntegerField()),
                ('label', models.CharField(null=True)),
                ('help', models.CharField(null=True)),
                ('kind', models.CharField(choices=[('scalar_column', 'Scalar column'), ('foreign_key', 'Foreign key')])),
                ('column_attnum', models.SmallIntegerField()),
                ('related_table_oid', models.PositiveBigIntegerField(null=True)),
                ('fk_interaction_rule', models.CharField(choices=[('must_pick', 'Must pick an existing record from the related table'), ('can_pick_or_create', 'Can pick an existing record from the related table or create a new record'), ('must_create', 'Must create a new record in the related table')], null=True)),
                ('styling', models.JSONField(null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='mathesar.form')),
                ('parent_field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_fields', to='mathesar.formfield')),
            ],
        ),
        migrations.AddConstraint(
            model_name='formfield',
            constraint=models.UniqueConstraint(fields=('key', 'form'), name='form_field_unique_key_per_form'),
        ),
        migrations.AddConstraint(
            model_name='formfield',
            constraint=models.CheckConstraint(check=models.Q(('kind', 'scalar_column'), models.Q(('fk_interaction_rule__isnull', False), ('kind', 'foreign_key'), ('related_table_oid__isnull', False)), _connector='OR'), name='form_field_kind_integrity'),
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE mathesar_form
            ADD CONSTRAINT form_database_server_integrity
              FOREIGN KEY (database_id, server_id)
              REFERENCES mathesar_database(id, server_id);
            """,
            reverse_sql="""
            ALTER TABLE mathesar_form
            DROP CONSTRAINT form_database_server_integrity;
            """
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE mathesar_form
            ADD CONSTRAINT form_role_server_integrity
              FOREIGN KEY (associated_role_id, server_id)
              REFERENCES mathesar_configuredrole(id, server_id);
            """,
            reverse_sql="""
            ALTER TABLE mathesar_form
            DROP CONSTRAINT form_role_server_integrity;
            """
        ),
        migrations.AddField(
            model_name='analyticsreport',
            name='form_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analyticsreport',
            name='public_form_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
