# Generated by Django 3.1.14 on 2023-09-11 19:07

from django.db import migrations, models
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0006_auto_20230906_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='database',
            name='host',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='database',
            name='password',
            field=encrypted_fields.fields.EncryptedCharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='database',
            name='port',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='database',
            name='username',
            field=encrypted_fields.fields.EncryptedCharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
