# Generated by Django 3.1.7 on 2021-06-16 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0005_auto_20210614_2137'),
        ('mathesar', '0006_auto_20210615_1729'),
    ]

    operations = [
    ]
