# Generated by Django 4.2.22 on 2025-08-27 06:51

from django.db import migrations, models
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('mathesar', '0006_analyticsreport_sso_connected_user_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mash', models.CharField(editable=False, primary_key=True, serialize=False)),
                ('uri', models.CharField()),
                ('thumbnail', models.JSONField(blank=True, default=dict)),
                ('fsspec_kwargs', encrypted_fields.fields.EncryptedJSONField(blank=True, default=dict)),
                ('sessions', models.ManyToManyField(to='sessions.session')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
