# Generated by Django 3.1.14 on 2022-11-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0006_auto_20221110_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='uiquery',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
