# Generated by Django 3.1.14 on 2023-09-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0006_auto_20230906_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablesettings',
            name='column_order',
            field=models.JSONField(default=None, null=True),
        ),
    ]
