# Generated by Django 4.2.11 on 2024-06-13 09:05

from django.db import migrations, models
import django.db.models.deletion
import mathesar.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0006_mathesar_databases_to_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Database',
            new_name='Connection',
        ),
        migrations.AlterField(
            model_name='databaserole',
            name='database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathesar.connection'),
        ),
        migrations.AlterField(
            model_name='schemarole',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathesar.schema'),
        ),
        migrations.AlterField(
            model_name='tablesettings',
            name='column_order',
            field=models.JSONField(blank=True, default=None, null=True, validators=[mathesar.models.base.validate_column_order]),
        ),
    ]
