# Generated by Django 4.2.11 on 2024-06-12 05:43

from django.db import migrations, models
import django.db.models.deletion
import mathesar.models.base


def update_db_server_info(apps, _):
    Database = apps.get_model('mathesar', 'Database')
    Server = apps.get_model('mathesar', 'Server')

    for database in Database.current_objects.all():
        database.server = Server.objects.get_or_create(host=database.host, port=database.port)[0]
        database.save()

class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0006_mathesar_databases_to_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='database',
            name='server',
            field=models.PositiveIntegerField()
        ),
        migrations.RunPython(update_db_server_info),
        migrations.AlterField(
            model_name='database',
            name='server',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='databases',
                to='mathesar.server'
            ),
        ),
        migrations.RemoveField(model_name='database', name='host'),
        migrations.RemoveField(model_name='database', name='port'),

        migrations.RenameField(model_name='database', old_name='name', new_name='display_name'),
        migrations.RenameField(model_name='database', old_name='db_name', new_name='name'),
    ]
