# Generated by Django 3.1.14 on 2022-11-18 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0007_auto_20221115_0627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='databaserole',
            options={'default_related_name': 'database_role'},
        ),
        migrations.AlterModelOptions(
            name='schemarole',
            options={'default_related_name': 'schema_role'},
        ),
        migrations.AlterField(
            model_name='databaserole',
            name='database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='database_role', to='mathesar.database'),
        ),
        migrations.AlterField(
            model_name='schemarole',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schema_role', to='mathesar.schema'),
        ),
    ]
