# Generated by Django 4.2.22 on 2025-08-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0007_downloadlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadlink',
            name='uri',
            field=models.CharField(),
        ),
    ]
