# Generated by Django 3.1.7 on 2021-06-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0007_merge_20210616_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='delimiter',
            field=models.CharField(blank=True, default=',', max_length=1),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='quotechar',
            field=models.CharField(blank=True, default='"', max_length=1),
        ),
    ]
