# Generated by Django 3.1.14 on 2023-09-21 18:07

from django.db import migrations, models
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0007_auto_20230913_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='db_name',
            field=models.CharField(default='', max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='database',
            name='editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='database',
            name='host',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='database',
            name='password',
            field=encrypted_fields.fields.EncryptedCharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='database',
            name='port',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='database',
            name='username',
            field=encrypted_fields.fields.EncryptedCharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tablesettings',
            name='column_order',
            field=models.JSONField(default=None, null=True),
        ),
    ]
