# Generated by Django 3.1.14 on 2022-11-23 14:23

from django.db import migrations, models
import mathesar.models.query


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='uiquery',
            name='display_names',
            field=models.JSONField(blank=True, null=True, validators=[mathesar.models.query.DictValidator]),
        ),
    ]
