# Generated by Django 3.1.7 on 2021-06-18 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0008_auto_20210617_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schema',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='table',
            name='deleted',
        ),
    ]
