# Generated by Django 3.1.14 on 2023-09-21 18:35

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0008_auto_20230921_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='password',
            field=encrypted_fields.fields.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='database',
            name='username',
            field=encrypted_fields.fields.EncryptedCharField(max_length=255),
        ),
    ]
