# Generated by Django 3.1.14 on 2023-10-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0008_auto_20230921_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='deleted',
        ),
        migrations.AlterField(
            model_name='tablesettings',
            name='column_order',
            field=models.JSONField(default=None, null=True),
        ),
    ]
