# Generated by Django 4.2.22 on 2025-09-08 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0008_downloadlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnmetadata',
            name='file_backend',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
