# Generated by Django 3.1.14 on 2023-10-25 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0008_auto_20230921_1834'),
        ('mathesar', '0005_user_display_language'),
    ]

    operations = [
    ]
