# Generated by Django 4.2.22 on 2025-08-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0008_alter_downloadlink_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadlink',
            name='thumbnail',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
