# Generated by Django 4.2.11 on 2024-07-01 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0008_add_metadata_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnmetadata',
            name='attnum',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='columnmetadata',
            name='num_max_frac_digits',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='columnmetadata',
            name='num_min_frac_digits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='columnmetadata',
            name='table_oid',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.CreateModel(
            name='TableMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table_oid', models.PositiveBigIntegerField()),
                ('import_verified', models.BooleanField(default=False)),
                ('column_order', models.JSONField(default=list)),
                ('record_summary_customized', models.BooleanField(default=False)),
                ('record_summary_template', models.CharField(blank=True, max_length=255)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathesar.database')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tablemetadata',
            constraint=models.UniqueConstraint(fields=('database', 'table_oid'), name='unique_table_metadata'),
        ),
    ]
