# Generated by Django 3.1.14 on 2023-11-04 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0005_auto_20231104_1022'),
        ('mathesar', '0009_merge_20231025_1733'),
    ]

    operations = [
    ]
