# Generated by Django 4.2.22 on 2025-08-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('mathesar', '0009_downloadlink_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadlink',
            name='session',
        ),
        migrations.AddField(
            model_name='downloadlink',
            name='sessions',
            field=models.ManyToManyField(to='sessions.session'),
        ),
        migrations.AlterField(
            model_name='downloadlink',
            name='uri',
            field=models.CharField(unique=True),
        ),
    ]
