# Generated by Django 4.2.26 on 2025-11-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0009_columnmetadata_file_backend'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsreport',
            name='postgres_deprecated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='analyticsreport',
            name='postgres_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='analyticsreport',
            name='mathesar_version',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='columnmetadata',
            name='bool_false',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='columnmetadata',
            name='bool_input',
            field=models.CharField(choices=[('dropdown', 'dropdown'), ('checkbox', 'checkbox')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='columnmetadata',
            name='bool_true',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='columnmetadata',
            name='date_format',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='columnmetadata',
            name='mon_currency_location',
            field=models.CharField(choices=[('after-minus', 'after-minus'), ('end-with-space', 'end-with-space')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='columnmetadata',
            name='mon_currency_symbol',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='columnmetadata',
            name='num_format',
            field=models.CharField(choices=[('english', 'english'), ('german', 'german'), ('french', 'french'), ('hindi', 'hindi'), ('swiss', 'swiss')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='columnmetadata',
            name='num_grouping',
            field=models.CharField(choices=[('always', 'always'), ('auto', 'auto'), ('never', 'never')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='columnmetadata',
            name='time_format',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='last_confirmed_sql_version',
            field=models.CharField(default='0.0.0', max_length=50),
        ),
        migrations.AlterField(
            model_name='database',
            name='nickname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='downloadlink',
            name='mash',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='downloadlink',
            name='uri',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='explorations',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='form',
            name='submit_button_label',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='fk_interaction_rule',
            field=models.CharField(choices=[('must_pick', 'Must pick an existing record from the related table'), ('can_pick_or_create', 'Can pick an existing record from the related table or create a new record'), ('must_create', 'Must create a new record in the related table')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='help',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='kind',
            field=models.CharField(choices=[('scalar_column', 'Scalar column'), ('foreign_key', 'Foreign key')], max_length=50),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='label',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
