# Generated by Django 3.1.14 on 2023-11-07 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0009_merge_20231025_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='editable',
        ),
    ]
