# Generated by Django 3.1.14 on 2023-12-13 20:03

import django.contrib.postgres.fields
from django.db import migrations, models
import mathesar.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0010_remove_editable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constraint',
            name='oid',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='schema',
            name='oid',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='oid',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tablesettings',
            name='column_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), default=None, null=True, size=None, validators=[mathesar.models.base.validate_column_order]),
        ),
    ]
