# Generated by Django 4.2.26 on 2026-01-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0010_server_sslmode'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='postgresql_version',
            field=models.IntegerField(null=True),
        ),
    ]
