# Generated by Django 4.2.11 on 2024-07-11 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0010_alter_tablemetadata_column_order_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Role',
            new_name='ConfiguredRole',
        ),
    ]
