# Generated by Django 3.1.14 on 2024-01-03 21:20

from django.db import migrations, models
import mathesar.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0010_remove_editable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constraint',
            name='oid',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='schema',
            name='oid',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='oid',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tablesettings',
            name='column_order',
            field=models.JSONField(blank=True, default=None, null=True, validators=[mathesar.models.base.validate_column_order]),
        ),
    ]
