# Generated by Django 4.2.22 on 2025-08-12 15:45

from django.db import migrations, models
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0010_remove_downloadlink_session_downloadlink_sessions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadlink',
            name='fsspec_kwargs',
            field=encrypted_fields.fields.EncryptedJSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='downloadlink',
            name='uri',
            field=models.CharField(),
        ),
        migrations.AddConstraint(
            model_name='downloadlink',
            constraint=models.UniqueConstraint(fields=('uri', 'fsspec_kwargs'), name='one_uri_copy_per_backend'),
        ),
    ]
