# Generated by Django 4.2.11 on 2024-07-15 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0010_alter_tablemetadata_column_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Explorations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_table_oid', models.PositiveBigIntegerField()),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.CharField(null=True)),
                ('initial_columns', models.JSONField()),
                ('transformations', models.JSONField(null=True)),
                ('display_options', models.JSONField(null=True)),
                ('display_names', models.JSONField()),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathesar.database')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
