# Generated by Django 3.1.14 on 2022-12-12 21:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0011_auto_20221208_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablesettings',
            name='column_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=None, null=True, size=None),
        ),
    ]
