# Generated by Django 3.1.7 on 2021-07-13 23:22

from django.db import migrations


def forwards_func(apps, schema_editor):
    Database = apps.get_model("mathesar", "Database")
    Schema = apps.get_model("mathesar", "Schema")
    for schema in Schema.objects.all():
        db, created = Database.objects.get_or_create(name=schema.database)
        schema.database_link = db
        schema.save()


def reverse_func(apps, schema_editor):
    # Having this here as an empty function means we can roll back this migration,
    # with the caveat that the database will still have the changes made here.
    # Given that this only modifies fields introduced in the PR this was written in,
    # it shouldn't be problematic.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0011_schema_database_link'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
