# Generated by Django 3.1.7 on 2021-07-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0011_auto_20210707_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='deleted',
            field=models.BooleanField(blank=True, default=False, unique=True),
        ),
    ]
