# Generated by Django 4.2.28 on 2026-05-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0011_columnmetadata_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
