# Generated by Django 4.2.11 on 2024-07-18 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0011_explorations'),
        ('mathesar', '0011_rename_role_configuredrole'),
    ]

    operations = [
    ]
