# Generated by Django 4.2.29 on 2026-05-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0012_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='encoding',
            field=models.CharField(default='utf-8', max_length=32),
        ),
    ]
