# Generated by Django 3.1.14 on 2023-01-19 13:03

from django.db import migrations, models
import mathesar.models.query


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0012_auto_20221212_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uiquery',
            name='display_names',
            field=models.JSONField(blank=True, null=True, validators=[mathesar.models.query.DictValidator(field_name='display_names')]),
        ),
        migrations.AlterField(
            model_name='uiquery',
            name='display_options',
            field=models.JSONField(blank=True, null=True, validators=[mathesar.models.query.DictValidator(field_name='display_options')]),
        ),
        migrations.AlterField(
            model_name='uiquery',
            name='initial_columns',
            field=models.JSONField(validators=[mathesar.models.query.ListOfDictValidator(field_name='initial_columns'), mathesar.models.query.InitialColumnsValidator(field_name='initial_columns')]),
        ),
        migrations.AlterField(
            model_name='uiquery',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='uiquery',
            name='transformations',
            field=models.JSONField(blank=True, null=True, validators=[mathesar.models.query.ListOfDictValidator(field_name='transformations'), mathesar.models.query.TransformationsValidator(field_name='transformations')]),
        ),
    ]
