# Generated by Django 3.1.7 on 2021-07-13 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0012_transfer_database'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schema',
            name='database',
        ),
    ]
