# Generated by Django 4.2.11 on 2024-07-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0012_merge_20240718_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnmetadata',
            name='bool_false',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='columnmetadata',
            name='bool_input',
            field=models.CharField(choices=[('dropdown', 'dropdown'), ('checkbox', 'checkbox')], null=True),
        ),
        migrations.AlterField(
            model_name='columnmetadata',
            name='bool_true',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='columnmetadata',
            name='date_format',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='columnmetadata',
            name='duration_max',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='columnmetadata',
            name='duration_min',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='columnmetadata',
            name='duration_show_units',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='columnmetadata',
            name='mon_currency_location',
            field=models.CharField(choices=[('after-minus', 'after-minus'), ('end-with-space', 'end-with-space')], null=True),
        ),
        migrations.AlterField(
            model_name='columnmetadata',
            name='mon_currency_symbol',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='columnmetadata',
            name='num_max_frac_digits',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='columnmetadata',
            name='num_min_frac_digits',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='columnmetadata',
            name='num_show_as_perc',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='columnmetadata',
            name='time_format',
            field=models.CharField(null=True),
        ),
    ]
