# Generated by Django 3.1.7 on 2021-07-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0012_auto_20210707_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='deleted',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
