# Generated by Django 4.2.11 on 2024-07-31 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('mathesar', '0014_remove_columnmetadata_duration_show_units_and_more'), ('mathesar', '0015_alter_columnmetadata_num_grouping'), ('mathesar', '0016_alter_columnmetadata_num_grouping')]

    dependencies = [
        ('mathesar', '0013_alter_columnmetadata_bool_false_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='columnmetadata',
            name='duration_show_units',
        ),
        migrations.RemoveField(
            model_name='columnmetadata',
            name='num_show_as_perc',
        ),
        migrations.AddField(
            model_name='columnmetadata',
            name='num_format',
            field=models.CharField(choices=[('english', 'english'), ('german', 'german'), ('french', 'french'), ('hindi', 'hindi'), ('swiss', 'swiss')], null=True),
        ),
        migrations.AddField(
            model_name='columnmetadata',
            name='num_grouping',
            field=models.CharField(choices=[('always', 'always'), ('auto', 'auto'), ('never', 'never')], null=True),
        ),
    ]
