# Generated by Django 3.1.7 on 2021-07-13 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0013_remove_schema_database'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schema',
            name='database_link',
        ),
        migrations.AddField(
            model_name='schema',
            name='database',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schemas', to='mathesar.database'),
            preserve_default=False,
        ),
    ]
