# Generated by Django 4.2.11 on 2024-07-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0013_alter_columnmetadata_bool_false_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='columnmetadata',
            name='duration_show_units',
        ),
        migrations.RemoveField(
            model_name='columnmetadata',
            name='num_show_as_perc',
        ),
        migrations.AddField(
            model_name='columnmetadata',
            name='num_format',
            field=models.CharField(choices=[('english', 'english'), ('german', 'german'), ('french', 'french'), ('hindi', 'hindi'), ('swiss', 'swiss')], null=True),
        ),
        migrations.AddField(
            model_name='columnmetadata',
            name='num_grouping',
            field=models.CharField(choices=[('force-yes', 'force-yes'), ('force-no', 'force-no')], null=True),
        ),
    ]
