# Generated by Django 3.1.7 on 2021-07-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0014_auto_20210713_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='header',
            field=models.BooleanField(default=True),
        ),
    ]
