# Generated by Django 4.2.11 on 2024-07-31 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0014_remove_columnmetadata_duration_show_units_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnmetadata',
            name='num_grouping',
            field=models.BooleanField(null=True),
        ),
    ]
