# Generated by Django 4.2.11 on 2024-09-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0015_tablemetadata_data_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explorations',
            name='display_names',
            field=models.JSONField(null=True),
        ),
    ]
