# Generated by Django 4.2.11 on 2024-07-31 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0015_alter_columnmetadata_num_grouping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnmetadata',
            name='num_grouping',
            field=models.CharField(choices=[('always', 'always'), ('auto', 'auto'), ('never', 'never')], null=True),
        ),
    ]
