# Generated by Django 4.2.11 on 2024-09-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0016_alter_explorations_display_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='explorations',
            name='schema_oid',
            field=models.PositiveBigIntegerField(),
        ),
    ]
