# Generated by Django 4.2.11 on 2024-10-14 15:42

from django.db import migrations, models
import mathesar.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0017_explorations_schema_oid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafile',
            name='table_imported_to',
        ),
        migrations.AlterField(
            model_name='datafile',
            name='file',
            field=models.FileField(upload_to=mathesar.models.base.DataFile._user_directory_path),
        ),
    ]
