# Generated by Django 4.2.11 on 2024-10-15 10:18

from django.db import migrations, models
import mathesar.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0017_explorations_schema_oid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constraint',
            name='table',
        ),
        migrations.RemoveField(
            model_name='databaserole',
            name='database',
        ),
        migrations.RemoveField(
            model_name='databaserole',
            name='user',
        ),
        migrations.RemoveField(
            model_name='exploration',
            name='base_table',
        ),
        migrations.RemoveField(
            model_name='schema',
            name='database',
        ),
        migrations.RemoveField(
            model_name='schemarole',
            name='schema',
        ),
        migrations.RemoveField(
            model_name='schemarole',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sharedquery',
            name='query',
        ),
        migrations.RemoveField(
            model_name='sharedtable',
            name='table',
        ),
        migrations.RemoveField(
            model_name='table',
            name='import_target',
        ),
        migrations.RemoveField(
            model_name='table',
            name='schema',
        ),
        migrations.RemoveField(
            model_name='tablesettings',
            name='preview_settings',
        ),
        migrations.RemoveField(
            model_name='tablesettings',
            name='table',
        ),
        migrations.RemoveField(
            model_name='datafile',
            name='table_imported_to',
        ),
        migrations.AlterField(
            model_name='datafile',
            name='file',
            field=models.FileField(upload_to=mathesar.models.base.DataFile._user_directory_path),
        ),
        migrations.DeleteModel(
            name='Column',
        ),
        migrations.DeleteModel(
            name='Connection',
        ),
        migrations.DeleteModel(
            name='Constraint',
        ),
        migrations.DeleteModel(
            name='DatabaseRole',
        ),
        migrations.DeleteModel(
            name='Exploration',
        ),
        migrations.DeleteModel(
            name='PreviewColumnSettings',
        ),
        migrations.DeleteModel(
            name='Schema',
        ),
        migrations.DeleteModel(
            name='SchemaRole',
        ),
        migrations.DeleteModel(
            name='SharedQuery',
        ),
        migrations.DeleteModel(
            name='SharedTable',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
        migrations.DeleteModel(
            name='TableSettings',
        ),
    ]
