# Generated by Django 3.1.7 on 2021-07-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0017_datafile_base_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='base_name',
            field=models.CharField(max_length=100),
        ),
    ]
