# Generated by Django 4.2.11 on 2024-10-08 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0017_explorations_schema_oid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedtable',
            name='table',
        ),
        migrations.DeleteModel(
            name='SharedQuery',
        ),
        migrations.DeleteModel(
            name='SharedTable',
        ),
    ]
