# Generated by Django 4.2.11 on 2024-10-23 14:08

from django.db import migrations


def clear_record_summary_values(apps, schema_editor):
    TableMetadata = apps.get_model('mathesar', 'TableMetadata')
    TableMetadata.objects.update(record_summary_template=None)


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0018_remove_constraint_table_remove_databaserole_database_and_more'),
    ]

    operations = [
        migrations.RunPython(clear_record_summary_values),
    ]
