# Generated by Django 3.1.7 on 2021-08-02 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0017_auto_20210731_0107'),
        ('mathesar', '0018_auto_20210730_1857'),
    ]

    operations = [
    ]
