# Generated by Django 3.1.7 on 2021-08-03 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0017_constraint'),
        ('mathesar', '0018_auto_20210730_1857'),
    ]

    operations = [
    ]
