# Generated by Django 3.1.7 on 2021-08-04 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0019_merge_20210802_2148'),
        ('mathesar', '0019_merge_20210803_1905'),
    ]

    operations = [
    ]
