# Generated by Django 4.2.11 on 2024-10-15 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0019_remove_sharedtable_table_delete_sharedquery_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exploration',
        ),
    ]
