# Generated by Django 4.2.11 on 2024-10-15 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0020_delete_exploration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schemarole',
            name='schema',
        ),
        migrations.RemoveField(
            model_name='schemarole',
            name='user',
        ),
        migrations.DeleteModel(
            name='DatabaseRole',
        ),
        migrations.DeleteModel(
            name='SchemaRole',
        ),
    ]
