# Generated by Django 4.2.16 on 2024-11-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0020_remove_tablemetadata_record_summary_customized_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='last_confirmed_sql_version',
            field=models.CharField(default='0.0.0'),
        ),
    ]
