# Generated by Django 3.1.7 on 2021-08-19 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0021_auto_20210819_2020'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='table',
            name='unique_table',
        ),
    ]
