# Generated by Django 4.2.16 on 2024-11-25 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0021_database_last_confirmed_sql_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationID',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('value', models.UUIDField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mathesar_version', models.CharField()),
                ('user_count', models.PositiveIntegerField(blank=True, null=True)),
                ('active_user_count', models.PositiveIntegerField(blank=True, null=True)),
                ('configured_role_count', models.PositiveIntegerField(blank=True, null=True)),
                ('connected_database_count', models.PositiveIntegerField(blank=True, null=True)),
                ('connected_database_schema_count', models.PositiveIntegerField(blank=True, null=True)),
                ('connected_database_table_count', models.PositiveIntegerField(blank=True, null=True)),
                ('exploration_count', models.PositiveIntegerField(blank=True, null=True)),
                ('recent_dql_query_count', models.PositiveIntegerField(blank=True, null=True)),
                ('recent_dml_query_count', models.PositiveIntegerField(blank=True, null=True)),
                ('recent_ddl_query_count', models.PositiveIntegerField(blank=True, null=True)),
                ('installation_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mathesar.installationid')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
