# Generated by Django 4.2.11 on 2024-10-15 09:24

from django.db import migrations, models
import mathesar.models.deprecated


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0021_remove_schemarole_schema_remove_schemarole_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablesettings',
            name='column_order',
            field=models.JSONField(blank=True, default=None, null=True, validators=[mathesar.models.deprecated.validate_column_order]),
        ),
    ]
