# Generated by Django 4.2.16 on 2024-11-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0022_installationid_analyticsreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyticsreport',
            name='recent_ddl_query_count',
        ),
        migrations.RemoveField(
            model_name='analyticsreport',
            name='recent_dml_query_count',
        ),
        migrations.RemoveField(
            model_name='analyticsreport',
            name='recent_dql_query_count',
        ),
        migrations.AddField(
            model_name='analyticsreport',
            name='connected_database_record_count',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
