# Generated by Django 4.2.16 on 2024-11-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0023_remove_analyticsreport_recent_ddl_query_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsreport',
            name='uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
