# Generated by Django 3.1.12 on 2021-11-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0024_auto_20211112_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='display_options',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
