# Generated by Django 3.1.14 on 2022-05-19 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0027_auto_20220329_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviewColumnSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customized', models.BooleanField()),
                ('columns', models.ManyToManyField(to='mathesar.Column')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TableSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preview_columns', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mathesar.previewcolumnsettings')),
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mathesar.table')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
