# Generated by Django 3.1.14 on 2022-07-05 00:00

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0028_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviewColumnSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customized', models.BooleanField()),
                ('template', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TableSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preview_settings', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mathesar.previewcolumnsettings')),
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='mathesar.table')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UIQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('initial_columns', models.JSONField()),
                ('transformations', models.JSONField(blank=True, null=True)),
                ('display_options', models.JSONField(blank=True, null=True)),
                ('base_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathesar.table')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Query',
        ),
    ]
