# Generated by Django 3.1.14 on 2022-05-20 09:50

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0028_previewcolumnsettings_tablesettings'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tablesettings',
            managers=[
                ('current_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='tablesettings',
            name='table',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='table_settings', to='mathesar.table'),
        ),
    ]
