# Generated by Django 3.1.14 on 2022-05-20 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0029_auto_20220520_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablesettings',
            name='table',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='mathesar.table'),
        ),
    ]
