# Generated by Django 3.1.14 on 2022-07-12 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0030_auto_20220704_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uiquery',
            name='base_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mathesar.table'),
        ),
        migrations.AlterField(
            model_name='uiquery',
            name='initial_columns',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
