# Generated by Django 3.1.14 on 2022-07-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0030_auto_20220704_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='is_temp',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
