# Generated by Django 3.1.14 on 2022-07-05 21:57

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0030_auto_20220704_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviewColumnSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customized', models.BooleanField()),
                ('template', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TableSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preview_settings', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mathesar.previewcolumnsettings')),
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='mathesar.table')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
