# Generated by Django 3.1.14 on 2022-07-14 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0031_previewcolumnsettings_tablesettings'),
        ('mathesar', '0031_auto_20220712_1104'),
    ]

    operations = [
    ]
