# Generated by Django 3.1.14 on 2022-07-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathesar', '0031_auto_20220712_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='is_temp',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
