// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
// The generator does not conform to our eslint rules
/* eslint-disable eslint-comments/no-unlimited-disable */
/* eslint eslint-comments/disable-enable-pair: [error, {allowWholeFile: true}] */
/* eslint-disable */
import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
} from 'typesafe-i18n';

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = 'en';

export type Locales = 'en' | 'ja';

export type Translation = RootTranslation;

export type Translations = RootTranslation;

type RootTranslation = {
  importUploadPage: {
    /**
     * U​p​l​o​a​d​ ​a​ ​f​i​l​e
     */
    uploadAFile: string;
    /**
     * P​r​o​v​i​d​e​ ​a​ ​U​R​L​ ​t​o​ ​t​h​e​ ​f​i​l​e
     */
    provideUrlToFile: string;
    /**
     * C​o​p​y​ ​a​n​d​ ​P​a​s​t​e​ ​T​e​x​t
     */
    copyAndPasteText: string;
    /**
     * C​r​e​a​t​e​ ​a​ ​t​a​b​l​e​ ​b​y​ ​i​m​p​o​r​t​i​n​g​ ​y​o​u​r​ ​d​a​t​a
     */
    createATableByImporting: string;
    /**
     * L​a​r​g​e​ ​d​a​t​a​ ​s​e​t​s​ ​c​a​n​ ​s​o​m​e​t​i​m​e​s​ ​t​a​k​e​ ​s​e​v​e​r​a​l​ ​m​i​n​u​t​e​s​ ​t​o​ ​p​r​o​c​e​s​s​.​ ​P​l​e​a​s​e​ ​d​o​ ​n​o​t​ ​l​e​a​v​e​ ​t​h​i​s​ ​p​a​g​e​ ​o​r​ ​c​l​o​s​e​ ​t​h​e​ ​b​r​o​w​s​e​r​ ​t​a​b​ ​w​h​i​l​e​ ​t​h​e​ ​i​m​p​o​r​t​ ​i​s​ ​i​n​ ​p​r​o​g​r​e​s​s​.
     */
    largeDataTakesTimeWarning: string;
  };
  general: {
    /**
     * I​m​p​o​r​t
     */
    import: string;
    /**
     * D​a​t​a​ ​S​o​u​r​c​e
     */
    dataSource: string;
    /**
     * P​r​o​c​e​s​s​i​n​g​ ​D​a​t​a
     */
    processingData: string;
    /**
     * N​o​ ​f​i​l​e​ ​u​p​l​o​a​d​e​d
     */
    noFileUploaded: string;
  };
};

export type TranslationFunctions = {
  importUploadPage: {
    /**
     * Upload a file
     */
    uploadAFile: () => LocalizedString;
    /**
     * Provide a URL to the file
     */
    provideUrlToFile: () => LocalizedString;
    /**
     * Copy and Paste Text
     */
    copyAndPasteText: () => LocalizedString;
    /**
     * Create a table by importing your data
     */
    createATableByImporting: () => LocalizedString;
    /**
     * Large data sets can sometimes take several minutes to process. Please do not leave this page or close the browser tab while the import is in progress.
     */
    largeDataTakesTimeWarning: () => LocalizedString;
  };
  general: {
    /**
     * Import
     */
    import: () => LocalizedString;
    /**
     * Data Source
     */
    dataSource: () => LocalizedString;
    /**
     * Processing Data
     */
    processingData: () => LocalizedString;
    /**
     * No file uploaded
     */
    noFileUploaded: () => LocalizedString;
  };
};

export type Formatters = {};
