// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.

import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
} from 'typesafe-i18n';

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = 'en';

export type Locales = 'de' | 'en';

export type Translation = RootTranslation;

export type Translations = RootTranslation;

type RootTranslation = {
  /**
   * A​l​l​ ​D​a​t​a​b​a​s​e​s
   */
  allDatabases: string;
  /**
   * D​a​t​a​b​a​s​e​ ​w​i​t​h​ ​n​a​m​e​ ​<​>​d​a​t​a​b​a​s​e​N​a​m​e​<​>​ ​i​s​ ​n​o​t​ ​f​o​u​n​d​.
   */
  databaseWithNameNotFound: string;
};

export type TranslationFunctions = {
  /**
   * All Databases
   */
  allDatabases: () => LocalizedString;
  /**
   * Database with name <>databaseName<> is not found.
   */
  databaseWithNameNotFound: () => LocalizedString;
};

export type Formatters = {};
