export const abstractTypeCategory = {
  Boolean: 'boolean',
  Date: 'date',
  Time: 'time',
  DateTime: 'datetime',
  Duration: 'duration',
  Email: 'email',
  Money: 'money',
  Number: 'number',
  Text: 'text',
  Uri: 'uri',
  JsonArray: 'jsonlist',
  JsonObject: 'map',
  Array: 'array',
  Other: 'other',
} as const;
