export const DB_TYPES = {
  ARRAY: '_array',
  BIGINT: 'bigint',
  BIT: 'bit',
  BOOLEAN: 'boolean',
  BYTEA: 'bytea',
  CHAR: '"char"',
  CHARACTER_VARYING: 'character varying',
  CHARACTER: 'character',
  CIDR: 'cidr',
  DATE: 'date',
  DATERANGE: 'daterange',
  DECIMAL: 'decimal',
  DOUBLE_PRECISION: 'double precision',
  INET: 'inet',
  INT4RANGE: 'int4range',
  INT8RANGE: 'int8range',
  INTEGER: 'integer',
  INTERVAL: 'interval',
  JSON: 'json',
  JSONB: 'jsonb',
  LINE: 'line',
  MACADDR: 'macaddr',
  MONEY: 'money',
  MSAR__EMAIL: 'mathesar_types.email',
  MSAR__MATHESAR_JSON_ARRAY: 'mathesar_types.mathesar_json_array',
  MSAR__MATHESAR_JSON_OBJECT: 'mathesar_types.mathesar_json_object',
  MSAR__MATHESAR_MONEY: 'mathesar_types.mathesar_money',
  MSAR__MULTICURRENCY_MONEY: 'mathesar_types.multicurrency_money',
  MSAR__URI: 'mathesar_types.uri',
  NAME: 'name',
  NUMERIC: 'numeric',
  NUMRANGE: 'numrange',
  OID: 'oid',
  REAL: 'real',
  REGCLASS: 'regclass',
  SMALLINT: 'smallint',
  TEXT: 'text',
  TIME_WITH_TZ: 'time with time zone',
  TIME_WITHOUT_TZ: 'time without time zone',
  TIMESTAMP_WITH_TZ: 'timestamp with time zone',
  TIMESTAMP_WITHOUT_TZ: 'timestamp without time zone',
  TSRANGE: 'tsrange',
  TSTZRANGE: 'tstzrange',
  TSVECTOR: 'tsvector',
  UUID: 'uuid',
};
