name: Packages Mathesar

on:
  pull_request:
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
      - uses: actions/checkout@v4

      - name: Setup Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Run package.sh Script
        run: |
          chmod +x package.sh
          ./package.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mathesar-package
          path: dist/mathesar.tar.gz
