name: labeled issue auto move

on:
  issues:
    types: [labeled]

jobs:
  Move_Labeled_Issue_On_Project_Board:
    runs-on: ubuntu-latest
    steps:
    - name: Move meta issue ticket to the Meta issues column
      uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        project-url: "https://github.com/centerofci/mathesar/projects/2"
        label-name: "type: meta"
        column-name: "Meta issues"
        columns-to-ignore: "Meta issues"
        action-token: "${{ secrets.MATHESAR_GITHUB_TOKEN }}"

    - name: Move ready ticket to the Ready column
      uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        project-url: "https://github.com/centerofci/mathesar/projects/2"
        label-name: "status: ready"
        column-name: "Ready"
        columns-to-ignore: "Meta issues, Ready"
        action-token: "${{ secrets.MATHESAR_GITHUB_TOKEN }}"

    - name: Move detail needed ticket to the Detail needed column
      uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        project-url: "https://github.com/centerofci/mathesar/projects/2"
        label-name: "status: draft"
        column-name: "Draft"
        columns-to-ignore: "Meta issues, Draft"
        action-token: "${{ secrets.MATHESAR_GITHUB_TOKEN }}"

    - name: Move blocked ticket to the Blocked column
      uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        project-url: "https://github.com/centerofci/mathesar/projects/2"
        label-name: "status: blocked"
        column-name: "Blocked"
        columns-to-ignore: "Meta issues, Blocked"
        action-token: "${{ secrets.MATHESAR_GITHUB_TOKEN }}"

    - name: Remove future ticket from Backlog project
      uses: justgiveacar/move-labeled-or-milestoned-issue@v3.0
      with:
        project-url: "https://github.com/centerofci/mathesar/projects/1"
        label-name: "status: future"
        delete-card: "true"
        action-token: "${{ secrets.MATHESAR_GITHUB_TOKEN }}"

    - name: Move future ticket to Future project
      uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        project-url: "https://github.com/centerofci/mathesar/projects/2"
        label-name: "status: future"
        column-name: "Triage"
        action-token: "${{ secrets.MATHESAR_GITHUB_TOKEN }}"
